/**
 * Seed Known Offenders
 *
 * 100 convicted serial offenders from public record:
 * court documents, FBI profiles, Radford/FGCU database, academic sources.
 *
 * birth_year is used as a hard eliminate floor:
 *   a victim who disappeared before (birth_year + 14) cannot be attributed.
 *
 * Run: npx tsx scripts/seed-offenders.ts
 * Dry: npx tsx scripts/seed-offenders.ts --dry-run
 */

import * as dotenv from 'dotenv'
import { resolve } from 'path'
import { createClient } from '@supabase/supabase-js'

dotenv.config({ path: resolve(process.cwd(), '.env.local') })

const supabase = createClient(
  process.env.NEXT_PUBLIC_SUPABASE_URL!,
  process.env.SUPABASE_SERVICE_ROLE_KEY!,
)

interface OffenderSeed {
  name: string
  aliases?: string[]
  birth_year?: number
  status: string
  conviction_count?: number
  suspected_count?: number
  active_from?: number
  active_to?: number
  incarcerated_from?: number
  incarcerated_to?: number
  home_states?: string[]
  home_cities?: string[]
  travel_corridors?: string[]
  operation_states?: string[]
  victim_states?: string[]
  victim_cities?: string[]
  victim_sex?: string
  victim_races?: string[]
  victim_age_min?: number
  victim_age_max?: number
  victim_age_typical?: number
  mo_keywords?: string[]
  disposal_method?: string[]
  cause_of_death?: string[]
  signature_details?: string
  source_notes?: string
  wikipedia_slug?: string
}

const OFFENDERS: OffenderSeed[] = [

  // ── NORTHWEST ──────────────────────────────────────────────────────────────

  {
    name: 'Gary Ridgway',
    aliases: ['Green River Killer'],
    birth_year: 1949,
    status: 'incarcerated',
    conviction_count: 49, suspected_count: 71,
    active_from: 1982, active_to: 1998, incarcerated_from: 2003,
    home_states: ['WA'], home_cities: ['Auburn', 'Kent', 'Federal Way'],
    operation_states: ['WA', 'OR'], victim_states: ['WA', 'OR'],
    victim_sex: 'female', victim_races: ['white', 'black', 'asian', 'native_american'],
    victim_age_min: 14, victim_age_max: 38, victim_age_typical: 20,
    mo_keywords: ['sex_worker', 'highway_abduction', 'truck_stop', 'hitchhiker'],
    disposal_method: ['wooded', 'remote', 'clustered'],
    cause_of_death: ['strangulation'],
    signature_details: 'Manual strangulation. Dumped bodies in wooded clusters near Green River and highway corridors. Returned to victim sites. Posed some victims.',
    wikipedia_slug: 'Gary_Ridgway',
  },
  {
    name: 'Ted Bundy',
    birth_year: 1946,
    status: 'deceased',
    conviction_count: 30, suspected_count: 36,
    active_from: 1974, active_to: 1978, incarcerated_from: 1989,
    home_states: ['WA', 'UT', 'CO', 'FL'],
    home_cities: ['Seattle', 'Salt Lake City', 'Tallahassee'],
    travel_corridors: ['I-5', 'I-15', 'I-80'],
    operation_states: ['WA', 'OR', 'UT', 'CO', 'ID', 'FL', 'CA'],
    victim_states: ['WA', 'OR', 'UT', 'CO', 'ID', 'FL'],
    victim_sex: 'female', victim_races: ['white'],
    victim_age_min: 14, victim_age_max: 26, victim_age_typical: 19,
    mo_keywords: ['college_campus', 'hitchhiker', 'ruse_approach', 'abduction'],
    disposal_method: ['wooded', 'remote', 'hillside'],
    cause_of_death: ['blunt_force', 'strangulation'],
    signature_details: 'Approached victims under ruse (sling/injury). Targeted young women with long dark hair. Revisited body sites. Necrophilia documented.',
    wikipedia_slug: 'Ted_Bundy',
  },
  {
    name: 'Keith Hunter Jesperson',
    aliases: ['Happy Face Killer'],
    birth_year: 1955,
    status: 'incarcerated',
    conviction_count: 8, suspected_count: 166,
    active_from: 1990, active_to: 1995, incarcerated_from: 1995,
    home_states: ['OR', 'WA'], home_cities: ['Washougal'],
    travel_corridors: ['I-5', 'I-80', 'I-84'],
    operation_states: ['OR', 'WA', 'CA', 'WY', 'NE', 'FL'],
    victim_states: ['OR', 'WA', 'CA', 'WY', 'NE', 'FL'],
    victim_sex: 'female', victim_races: ['white'],
    victim_age_min: 18, victim_age_max: 41, victim_age_typical: 28,
    mo_keywords: ['hitchhiker', 'truck_stop', 'long_haul_trucker'],
    disposal_method: ['roadside', 'remote', 'highway'],
    cause_of_death: ['strangulation'],
    signature_details: 'Long-haul truck driver. Picked up hitchhikers. Sent smiley-face letters to media. Western interstate trucking corridors.',
    wikipedia_slug: 'Keith_Hunter_Jesperson',
  },
  {
    name: 'Robert Lee Yates',
    birth_year: 1952,
    status: 'incarcerated',
    conviction_count: 13, suspected_count: 16,
    active_from: 1975, active_to: 1998, incarcerated_from: 2000,
    home_states: ['WA'], home_cities: ['Spokane'],
    operation_states: ['WA'], victim_states: ['WA'],
    victim_sex: 'female', victim_races: ['white', 'black', 'native_american'],
    victim_age_min: 16, victim_age_max: 56, victim_age_typical: 35,
    mo_keywords: ['sex_worker', 'highway_abduction', 'car'],
    disposal_method: ['roadside', 'rural', 'buried'],
    cause_of_death: ['shooting', 'strangulation'],
    signature_details: 'Targeted sex workers in Spokane area. Shot victims in head. Buried one victim in own backyard.',
    wikipedia_slug: 'Robert_Lee_Yates',
  },
  {
    name: 'Westley Allan Dodd',
    birth_year: 1961,
    status: 'deceased',
    conviction_count: 3, suspected_count: 3,
    active_from: 1981, active_to: 1989, incarcerated_from: 1990,
    home_states: ['WA', 'ID'], home_cities: ['Vancouver WA', 'Kennewick'],
    operation_states: ['WA', 'ID', 'OR'],
    victim_states: ['WA'],
    victim_sex: 'male', victim_races: ['white'],
    victim_age_min: 6, victim_age_max: 13, victim_age_typical: 10,
    mo_keywords: ['children', 'neighborhood', 'park', 'lured'],
    disposal_method: ['wooded', 'left_in_place'],
    cause_of_death: ['stabbing', 'blunt_force', 'asphyxiation'],
    signature_details: 'Targeted young boys in parks and neighborhoods. Kept detailed diary. Executed by hanging 1993.',
    wikipedia_slug: 'Westley_Allan_Dodd',
  },
  {
    name: 'Randy Kraft',
    aliases: ['Scorecard Killer', 'Freeway Killer'],
    birth_year: 1945,
    status: 'incarcerated',
    conviction_count: 16, suspected_count: 67,
    active_from: 1971, active_to: 1983, incarcerated_from: 1989,
    home_states: ['CA', 'OR'], home_cities: ['Long Beach', 'Stanton'],
    travel_corridors: ['I-5', 'I-405', 'PCH'],
    operation_states: ['CA', 'OR', 'MI'],
    victim_states: ['CA', 'OR', 'MI'],
    victim_sex: 'male', victim_races: ['white'],
    victim_age_min: 13, victim_age_max: 35, victim_age_typical: 20,
    mo_keywords: ['hitchhiker', 'military', 'young_male', 'highway_abduction'],
    disposal_method: ['roadside', 'highway'],
    cause_of_death: ['strangulation', 'asphyxiation'],
    signature_details: 'Picked up hitchhikers and military men along California freeways. Kept coded scorecard. Victims found along highway shoulders.',
    wikipedia_slug: 'Randy_Kraft',
  },
  {
    name: 'Robert Hansen',
    aliases: ['Butcher Baker'],
    birth_year: 1939,
    status: 'deceased',
    conviction_count: 4, suspected_count: 21,
    active_from: 1971, active_to: 1983, incarcerated_from: 1984,
    home_states: ['AK'], home_cities: ['Anchorage'],
    operation_states: ['AK'], victim_states: ['AK'],
    victim_sex: 'female', victim_races: ['white', 'native_american'],
    victim_age_min: 16, victim_age_max: 30, victim_age_typical: 22,
    mo_keywords: ['sex_worker', 'hitchhiker', 'strip_club', 'abduction'],
    disposal_method: ['remote', 'wilderness', 'buried'],
    cause_of_death: ['shooting', 'strangulation'],
    signature_details: 'Flew victims to remote Alaskan wilderness and hunted them. Kept trophy maps of burial sites.',
    wikipedia_slug: 'Robert_Hansen',
  },

  // ── CALIFORNIA ─────────────────────────────────────────────────────────────

  {
    name: 'Samuel Little',
    aliases: ['The Most Prolific US Serial Killer'],
    birth_year: 1940,
    status: 'deceased',
    conviction_count: 8, suspected_count: 93,
    active_from: 1970, active_to: 2005, incarcerated_from: 2012,
    home_states: ['CA', 'OH', 'TX', 'MS', 'GA'],
    home_cities: ['Los Angeles', 'Odessa', 'San Diego'],
    travel_corridors: ['I-10', 'I-20', 'I-40'],
    operation_states: ['CA', 'TX', 'MS', 'AL', 'GA', 'FL', 'OH', 'KY', 'TN', 'LA', 'NM', 'NV', 'AZ', 'MO', 'AR', 'SC', 'MD'],
    victim_states: ['CA', 'TX', 'MS', 'AL', 'GA', 'FL', 'OH', 'KY', 'TN'],
    victim_sex: 'female', victim_races: ['black', 'white', 'hispanic'],
    victim_age_min: 16, victim_age_max: 62, victim_age_typical: 30,
    mo_keywords: ['sex_worker', 'drug_user', 'bar', 'marginalized', 'hitchhiker'],
    disposal_method: ['roadside', 'wooded', 'alley'],
    cause_of_death: ['strangulation'],
    signature_details: 'Manual strangulation. FBI confirmed highest US victim count. Traveled extensively by car. Targeted women in vulnerable circumstances.',
    wikipedia_slug: 'Samuel_Little',
  },
  {
    name: 'Richard Ramirez',
    aliases: ['Night Stalker'],
    birth_year: 1960,
    status: 'deceased',
    conviction_count: 13, suspected_count: 14,
    active_from: 1984, active_to: 1985, incarcerated_from: 1989,
    home_states: ['CA'], home_cities: ['Los Angeles', 'San Francisco'],
    operation_states: ['CA'], victim_states: ['CA'],
    victim_sex: 'both', victim_races: ['white', 'hispanic', 'asian'],
    victim_age_min: 9, victim_age_max: 83, victim_age_typical: 55,
    mo_keywords: ['home_invasion', 'stalking', 'satanic', 'night_attack'],
    disposal_method: ['left_in_place'],
    cause_of_death: ['shooting', 'stabbing', 'blunt_force', 'strangulation'],
    signature_details: 'Nocturnal home invasions in LA and SF suburbs. Satanic imagery. Demanded victims swear to Satan. Wide age range of victims.',
    wikipedia_slug: 'Richard_Ramirez',
  },
  {
    name: 'William Bonin',
    aliases: ['Freeway Killer'],
    birth_year: 1947,
    status: 'deceased',
    conviction_count: 14, suspected_count: 21,
    active_from: 1979, active_to: 1980, incarcerated_from: 1980,
    home_states: ['CA'], home_cities: ['Downey', 'Gardena'],
    travel_corridors: ['I-5', 'I-405', 'I-605'],
    operation_states: ['CA'], victim_states: ['CA'],
    victim_sex: 'male', victim_races: ['white', 'hispanic'],
    victim_age_min: 14, victim_age_max: 19, victim_age_typical: 16,
    mo_keywords: ['hitchhiker', 'young_male', 'highway_abduction', 'van'],
    disposal_method: ['roadside', 'highway'],
    cause_of_death: ['strangulation', 'blunt_force'],
    signature_details: 'Operated van along southern California freeways. Picked up teenage hitchhikers. Operated with accomplices.',
    wikipedia_slug: 'William_Bonin',
  },
  {
    name: 'Patrick Kearney',
    aliases: ['Trash Bag Killer', 'Freeway Killer'],
    birth_year: 1939,
    status: 'incarcerated',
    conviction_count: 21, suspected_count: 43,
    active_from: 1962, active_to: 1977, incarcerated_from: 1977,
    home_states: ['CA'], home_cities: ['Redondo Beach', 'Culver City'],
    travel_corridors: ['I-405', 'I-5'],
    operation_states: ['CA', 'TX'], victim_states: ['CA'],
    victim_sex: 'male', victim_races: ['white', 'hispanic'],
    victim_age_min: 13, victim_age_max: 28, victim_age_typical: 20,
    mo_keywords: ['hitchhiker', 'young_male', 'gay_bar', 'highway_abduction'],
    disposal_method: ['roadside', 'trash_bag', 'freeway'],
    cause_of_death: ['shooting'],
    signature_details: 'Shot victims and dismembered some. Disposed of body parts in trash bags along freeways. Active longest confirmed period in CA.',
    wikipedia_slug: 'Patrick_Kearney',
  },
  {
    name: 'Angelo Buono Jr.',
    aliases: ['Hillside Strangler'],
    birth_year: 1934,
    status: 'deceased',
    conviction_count: 9, suspected_count: 10,
    active_from: 1977, active_to: 1978, incarcerated_from: 1983,
    home_states: ['CA'], home_cities: ['Glendale', 'Los Angeles'],
    operation_states: ['CA'], victim_states: ['CA'],
    victim_sex: 'female', victim_races: ['white', 'hispanic'],
    victim_age_min: 12, victim_age_max: 28, victim_age_typical: 18,
    mo_keywords: ['abduction', 'ruse_approach', 'fake_police', 'sex_worker'],
    disposal_method: ['hillside', 'roadside', 'left_in_place'],
    cause_of_death: ['strangulation', 'asphyxiation'],
    signature_details: 'Operated with cousin Kenneth Bianchi. Posed as police to abduct women. Bodies dumped on LA hillsides.',
    wikipedia_slug: 'Angelo_Buono_Jr.',
  },
  {
    name: 'Edmund Kemper',
    aliases: ['Co-ed Killer', 'Big Ed'],
    birth_year: 1948,
    status: 'incarcerated',
    conviction_count: 10, suspected_count: 10,
    active_from: 1964, active_to: 1973, incarcerated_from: 1973,
    home_states: ['CA'], home_cities: ['Santa Cruz', 'Aptos'],
    operation_states: ['CA'], victim_states: ['CA'],
    victim_sex: 'female', victim_races: ['white'],
    victim_age_min: 15, victim_age_max: 72, victim_age_typical: 20,
    mo_keywords: ['hitchhiker', 'college_campus', 'car_lure', 'necrophilia'],
    disposal_method: ['remote', 'buried', 'scattered'],
    cause_of_death: ['shooting', 'stabbing', 'strangulation'],
    signature_details: 'Picked up hitchhikers near UC Santa Cruz. Necrophilia and dismemberment. Also killed grandparents and mother.',
    wikipedia_slug: 'Edmund_Kemper',
  },
  {
    name: 'Herbert Mullin',
    birth_year: 1947,
    status: 'incarcerated',
    conviction_count: 13, suspected_count: 13,
    active_from: 1972, active_to: 1973, incarcerated_from: 1973,
    home_states: ['CA'], home_cities: ['Santa Cruz', 'Los Gatos'],
    operation_states: ['CA'], victim_states: ['CA'],
    victim_sex: 'both', victim_races: ['white'],
    victim_age_min: 4, victim_age_max: 72, victim_age_typical: 25,
    mo_keywords: ['hitchhiker', 'random', 'schizophrenic', 'opportunistic'],
    disposal_method: ['remote', 'wooded', 'left_in_place'],
    cause_of_death: ['stabbing', 'shooting', 'blunt_force'],
    signature_details: 'Believed murders would prevent earthquakes. Random victim selection. Active in Santa Cruz mountains concurrent with Kemper.',
    wikipedia_slug: 'Herbert_Mullin',
  },
  {
    name: 'Harvey Glatman',
    aliases: ['Lonely Hearts Killer'],
    birth_year: 1927,
    status: 'deceased',
    conviction_count: 3, suspected_count: 3,
    active_from: 1957, active_to: 1958, incarcerated_from: 1958,
    home_states: ['CA'], home_cities: ['Los Angeles'],
    operation_states: ['CA'], victim_states: ['CA'],
    victim_sex: 'female', victim_races: ['white'],
    victim_age_min: 19, victim_age_max: 24, victim_age_typical: 22,
    mo_keywords: ['modeling_ruse', 'photography_ruse', 'lonely_hearts', 'dating'],
    disposal_method: ['desert', 'remote'],
    cause_of_death: ['strangulation'],
    signature_details: 'Posed as photographer to lure models. Bondage photography. Dumped bodies in California and Arizona desert.',
    wikipedia_slug: 'Harvey_Glatman',
  },
  {
    name: 'Juan Corona',
    birth_year: 1934,
    status: 'deceased',
    conviction_count: 25, suspected_count: 25,
    active_from: 1971, active_to: 1971, incarcerated_from: 1971,
    home_states: ['CA'], home_cities: ['Yuba City', 'Marysville'],
    operation_states: ['CA'], victim_states: ['CA'],
    victim_sex: 'male', victim_races: ['white', 'hispanic'],
    victim_age_min: 40, victim_age_max: 67, victim_age_typical: 55,
    mo_keywords: ['migrant_worker', 'farm_labor', 'transient', 'drifter'],
    disposal_method: ['buried', 'orchard'],
    cause_of_death: ['stabbing', 'blunt_force'],
    signature_details: 'Killed migrant farmworkers and buried them in peach orchards near Yuba City. Labor contractor.',
    wikipedia_slug: 'Juan_Corona',
  },
  {
    name: 'Lonnie Franklin Jr.',
    aliases: ['Grim Sleeper'],
    birth_year: 1952,
    status: 'deceased',
    conviction_count: 10, suspected_count: 25,
    active_from: 1985, active_to: 2007, incarcerated_from: 2010,
    home_states: ['CA'], home_cities: ['Los Angeles', 'South Los Angeles'],
    operation_states: ['CA'], victim_states: ['CA'],
    victim_sex: 'female', victim_races: ['black'],
    victim_age_min: 14, victim_age_max: 35, victim_age_typical: 22,
    mo_keywords: ['sex_worker', 'drug_user', 'south_la', 'marginalized'],
    disposal_method: ['alley', 'dumpster', 'roadside'],
    cause_of_death: ['shooting', 'strangulation'],
    signature_details: 'Active in South Los Angeles. 14-year apparent gap in activity. Targeted Black women from marginalized communities.',
    wikipedia_slug: 'Lonnie_Franklin_Jr.',
  },
  {
    name: 'Chester Turner',
    birth_year: 1966,
    status: 'incarcerated',
    conviction_count: 14, suspected_count: 16,
    active_from: 1987, active_to: 1998, incarcerated_from: 2003,
    home_states: ['CA'], home_cities: ['Los Angeles', 'South Los Angeles'],
    operation_states: ['CA'], victim_states: ['CA'],
    victim_sex: 'female', victim_races: ['black'],
    victim_age_min: 15, victim_age_max: 44, victim_age_typical: 27,
    mo_keywords: ['sex_worker', 'drug_user', 'south_la', 'strangulation'],
    disposal_method: ['alley', 'roadside', 'dumpster'],
    cause_of_death: ['strangulation'],
    signature_details: 'South LA strangulator. DNA connected to Grim Sleeper-era cases. Targeted vulnerable women in same geographic area as Franklin.',
    wikipedia_slug: 'Chester_Turner',
  },
  {
    name: 'Wayne Adam Ford',
    birth_year: 1961,
    status: 'incarcerated',
    conviction_count: 4, suspected_count: 4,
    active_from: 1997, active_to: 1998, incarcerated_from: 1998,
    home_states: ['CA'], home_cities: ['Arcata', 'Eureka'],
    travel_corridors: ['US-101', 'I-5'],
    operation_states: ['CA'], victim_states: ['CA'],
    victim_sex: 'female', victim_races: ['white'],
    victim_age_min: 18, victim_age_max: 29, victim_age_typical: 24,
    mo_keywords: ['hitchhiker', 'truck_driver', 'sex_worker'],
    disposal_method: ['remote', 'wooded', 'water'],
    cause_of_death: ['strangulation'],
    signature_details: 'Trucker who walked into sheriff\'s office carrying severed breast of victim. Confessed to 4 killings.',
    wikipedia_slug: 'Wayne_Adam_Ford',
  },
  {
    name: 'Douglas Clark',
    aliases: ['Sunset Strip Killer'],
    birth_year: 1948,
    status: 'incarcerated',
    conviction_count: 6, suspected_count: 7,
    active_from: 1980, active_to: 1980, incarcerated_from: 1980,
    home_states: ['CA'], home_cities: ['Burbank', 'Los Angeles'],
    operation_states: ['CA'], victim_states: ['CA'],
    victim_sex: 'female', victim_races: ['white'],
    victim_age_min: 11, victim_age_max: 24, victim_age_typical: 17,
    mo_keywords: ['sex_worker', 'runaway', 'sunset_strip', 'car'],
    disposal_method: ['roadside', 'dumpster'],
    cause_of_death: ['shooting'],
    signature_details: 'Shot young women and runaways on Sunset Strip. Partner Carol Bundy also convicted. Decapitated some victims.',
    wikipedia_slug: 'Douglas_Clark_(murderer)',
  },
  {
    name: 'Cary Stayner',
    aliases: ['Yosemite Killer'],
    birth_year: 1961,
    status: 'incarcerated',
    conviction_count: 4, suspected_count: 4,
    active_from: 1999, active_to: 1999, incarcerated_from: 1999,
    home_states: ['CA'], home_cities: ['El Portal', 'Merced'],
    operation_states: ['CA'], victim_states: ['CA'],
    victim_sex: 'female', victim_races: ['white'],
    victim_age_min: 15, victim_age_max: 42, victim_age_typical: 26,
    mo_keywords: ['national_park', 'tourist', 'motel_worker', 'remote'],
    disposal_method: ['remote', 'wilderness', 'wooded'],
    cause_of_death: ['strangulation', 'decapitation'],
    signature_details: 'Worked at motel near Yosemite. Killed tourists. Decapitation. National park proximity pattern.',
    wikipedia_slug: 'Cary_Stayner',
  },

  // ── PACIFIC NORTHWEST / MOUNTAIN ───────────────────────────────────────────

  {
    name: 'John Norman Collins',
    aliases: ['Michigan Murderer', 'Co-ed Killer'],
    birth_year: 1947,
    status: 'incarcerated',
    conviction_count: 1, suspected_count: 7,
    active_from: 1967, active_to: 1969, incarcerated_from: 1970,
    home_states: ['MI'], home_cities: ['Ypsilanti', 'Ann Arbor'],
    operation_states: ['MI', 'CA'], victim_states: ['MI'],
    victim_sex: 'female', victim_races: ['white'],
    victim_age_min: 13, victim_age_max: 23, victim_age_typical: 19,
    mo_keywords: ['college_campus', 'motorcycle', 'hitchhiker', 'abduction'],
    disposal_method: ['remote', 'wooded', 'rural'],
    cause_of_death: ['strangulation', 'stabbing', 'shooting'],
    signature_details: 'EMU student who lured victims using motorcycle. All victims near University of Michigan / Eastern Michigan University.',
    wikipedia_slug: 'John_Norman_Collins',
  },

  // ── MIDWEST ────────────────────────────────────────────────────────────────

  {
    name: 'John Wayne Gacy',
    aliases: ['Killer Clown'],
    birth_year: 1942,
    status: 'deceased',
    conviction_count: 33, suspected_count: 33,
    active_from: 1972, active_to: 1978, incarcerated_from: 1994,
    home_states: ['IL'], home_cities: ['Chicago', 'Norwood Park'],
    operation_states: ['IL'], victim_states: ['IL'],
    victim_sex: 'male', victim_races: ['white', 'hispanic'],
    victim_age_min: 14, victim_age_max: 21, victim_age_typical: 17,
    mo_keywords: ['young_male', 'labor_ruse', 'bar', 'gay_bar', 'lured'],
    disposal_method: ['buried', 'in_structure', 'river'],
    cause_of_death: ['strangulation', 'asphyxiation'],
    signature_details: 'Lured young men via employment or gay bars. Buried 26 victims under house crawl space. Used chloroform and rope gag.',
    wikipedia_slug: 'John_Wayne_Gacy',
  },
  {
    name: 'Jeffrey Dahmer',
    aliases: ['Milwaukee Cannibal', 'Milwaukee Monster'],
    birth_year: 1960,
    status: 'deceased',
    conviction_count: 17, suspected_count: 17,
    active_from: 1978, active_to: 1991, incarcerated_from: 1991,
    home_states: ['WI', 'OH'], home_cities: ['Milwaukee', 'Bath Township OH'],
    operation_states: ['WI', 'OH'], victim_states: ['WI', 'OH'],
    victim_sex: 'male', victim_races: ['black', 'hispanic', 'asian', 'white'],
    victim_age_min: 14, victim_age_max: 33, victim_age_typical: 22,
    mo_keywords: ['young_male', 'gay_bar', 'lured', 'drug_ruse', 'bar'],
    disposal_method: ['in_structure', 'dissolved', 'stored'],
    cause_of_death: ['strangulation', 'blunt_force'],
    signature_details: 'Lured men from gay bars and malls. Drugged victims. Necrophilia, dismemberment, cannibalism. Kept body parts.',
    wikipedia_slug: 'Jeffrey_Dahmer',
  },
  {
    name: 'Dennis Rader',
    aliases: ['BTK Killer'],
    birth_year: 1945,
    status: 'incarcerated',
    conviction_count: 10, suspected_count: 10,
    active_from: 1974, active_to: 1991, incarcerated_from: 2005,
    home_states: ['KS'], home_cities: ['Wichita', 'Park City'],
    operation_states: ['KS'], victim_states: ['KS'],
    victim_sex: 'both', victim_races: ['white'],
    victim_age_min: 9, victim_age_max: 62, victim_age_typical: 25,
    mo_keywords: ['home_invasion', 'stalking', 'bindings', 'targeted'],
    disposal_method: ['left_in_place', 'remote'],
    cause_of_death: ['strangulation', 'asphyxiation'],
    signature_details: 'Bind, torture, kill. Sent taunting letters to media and police. Stalked victims for months.',
    wikipedia_slug: 'BTK_killer',
  },
  {
    name: 'John Edward Robinson',
    aliases: ['Slavemaster'],
    birth_year: 1943,
    status: 'incarcerated',
    conviction_count: 8, suspected_count: 13,
    active_from: 1984, active_to: 1999, incarcerated_from: 2000,
    home_states: ['KS', 'MO'], home_cities: ['Olathe', 'Lenexa'],
    operation_states: ['KS', 'MO'], victim_states: ['KS', 'MO'],
    victim_sex: 'female', victim_races: ['white'],
    victim_age_min: 19, victim_age_max: 50, victim_age_typical: 30,
    mo_keywords: ['online', 'bdsm', 'vulnerable_women', 'job_ruse'],
    disposal_method: ['barrel', 'stored', 'farm'],
    cause_of_death: ['blunt_force'],
    signature_details: 'Early internet predator. BDSM communities. Stored bodies in barrels on farm property.',
    wikipedia_slug: 'John_Edward_Robinson',
  },
  {
    name: 'Lorenzo Gilyard',
    aliases: ['Kansas City Strangler'],
    birth_year: 1952,
    status: 'incarcerated',
    conviction_count: 13, suspected_count: 13,
    active_from: 1977, active_to: 1993, incarcerated_from: 2007,
    home_states: ['MO'], home_cities: ['Kansas City'],
    operation_states: ['MO'], victim_states: ['MO'],
    victim_sex: 'female', victim_races: ['black', 'white'],
    victim_age_min: 15, victim_age_max: 31, victim_age_typical: 22,
    mo_keywords: ['sex_worker', 'street_level', 'highway_abduction'],
    disposal_method: ['roadside', 'wooded', 'alley'],
    cause_of_death: ['strangulation'],
    signature_details: 'Targeted street-level sex workers in Kansas City over 16 years. DNA not matched until 2004.',
    wikipedia_slug: 'Lorenzo_Gilyard',
  },
  {
    name: 'Robert Berdella',
    aliases: ['Kansas City Butcher'],
    birth_year: 1949,
    status: 'deceased',
    conviction_count: 6, suspected_count: 6,
    active_from: 1984, active_to: 1987, incarcerated_from: 1988,
    home_states: ['MO'], home_cities: ['Kansas City'],
    operation_states: ['MO'], victim_states: ['MO'],
    victim_sex: 'male', victim_races: ['white'],
    victim_age_min: 18, victim_age_max: 23, victim_age_typical: 20,
    mo_keywords: ['young_male', 'lured', 'drug_ruse', 'home_based'],
    disposal_method: ['in_structure', 'dismembered', 'trash'],
    cause_of_death: ['torture', 'asphyxiation'],
    signature_details: 'Captured, tortured and held young men captive for days. Kept detailed logs. Flea market vendor.',
    wikipedia_slug: 'Robert_Berdella',
  },
  {
    name: 'Maury Travis',
    birth_year: 1965,
    status: 'deceased',
    conviction_count: 0, suspected_count: 17,
    active_from: 2001, active_to: 2002, incarcerated_from: 2002,
    home_states: ['MO'], home_cities: ['Ferguson', 'St. Louis'],
    operation_states: ['MO'], victim_states: ['MO'],
    victim_sex: 'female', victim_races: ['black'],
    victim_age_min: 16, victim_age_max: 35, victim_age_typical: 25,
    mo_keywords: ['sex_worker', 'drug_user', 'marginalized', 'lured'],
    disposal_method: ['wooded', 'remote', 'roadside'],
    cause_of_death: ['strangulation'],
    signature_details: 'Sent hand-drawn map of dump sites to newspaper. Suicide in custody. Targeted vulnerable Black women in St. Louis area.',
    wikipedia_slug: 'Maury_Travis',
  },
  {
    name: 'Larry Eyler',
    aliases: ['Highway Murderer'],
    birth_year: 1952,
    status: 'deceased',
    conviction_count: 21, suspected_count: 23,
    active_from: 1982, active_to: 1984, incarcerated_from: 1994,
    home_states: ['IL', 'IN'], home_cities: ['Chicago', 'Terre Haute'],
    travel_corridors: ['I-65', 'I-57'],
    operation_states: ['IL', 'IN', 'WI', 'OH'],
    victim_states: ['IL', 'IN', 'WI'],
    victim_sex: 'male', victim_races: ['white'],
    victim_age_min: 15, victim_age_max: 28, victim_age_typical: 19,
    mo_keywords: ['hitchhiker', 'young_male', 'highway_abduction', 'gay'],
    disposal_method: ['roadside', 'rural', 'field'],
    cause_of_death: ['stabbing', 'blunt_force'],
    signature_details: 'Picked up male hitchhikers along Illinois/Indiana highways. Victims bound and stabbed.',
    wikipedia_slug: 'Larry_Eyler',
  },
  {
    name: 'Arthur Shawcross',
    aliases: ['Genesee River Killer'],
    birth_year: 1945,
    status: 'deceased',
    conviction_count: 14, suspected_count: 14,
    active_from: 1972, active_to: 1990, incarcerated_from: 1991,
    home_states: ['NY'], home_cities: ['Rochester', 'Watertown'],
    operation_states: ['NY'], victim_states: ['NY'],
    victim_sex: 'both', victim_races: ['white', 'black'],
    victim_age_min: 10, victim_age_max: 59, victim_age_typical: 30,
    mo_keywords: ['sex_worker', 'riverside', 'hitchhiker'],
    disposal_method: ['water', 'riverside', 'wooded'],
    cause_of_death: ['strangulation', 'blunt_force'],
    signature_details: 'Targeted sex workers in Rochester. Disposed near Genesee River. Cannibalism documented.',
    wikipedia_slug: 'Arthur_Shawcross',
  },
  {
    name: 'Joel Rifkin',
    birth_year: 1959,
    status: 'incarcerated',
    conviction_count: 9, suspected_count: 17,
    active_from: 1989, active_to: 1993, incarcerated_from: 1993,
    home_states: ['NY'], home_cities: ['East Meadow', 'New York City'],
    operation_states: ['NY', 'NJ'], victim_states: ['NY', 'NJ'],
    victim_sex: 'female', victim_races: ['white', 'black', 'hispanic'],
    victim_age_min: 18, victim_age_max: 35, victim_age_typical: 25,
    mo_keywords: ['sex_worker', 'new_york_city', 'car', 'highway'],
    disposal_method: ['water', 'wooded', 'scattered'],
    cause_of_death: ['strangulation'],
    signature_details: 'Picked up sex workers in NYC. Strangled them in his truck. Dismembered and disposed in multiple locations.',
    wikipedia_slug: 'Joel_Rifkin',
  },
  {
    name: 'Leslie Allen Williams',
    birth_year: 1956,
    status: 'incarcerated',
    conviction_count: 4, suspected_count: 4,
    active_from: 1991, active_to: 1992, incarcerated_from: 1993,
    home_states: ['MI'], home_cities: ['Lake Orion', 'Oakland County'],
    operation_states: ['MI'], victim_states: ['MI'],
    victim_sex: 'female', victim_races: ['white'],
    victim_age_min: 14, victim_age_max: 27, victim_age_typical: 18,
    mo_keywords: ['hitchhiker', 'abduction', 'roadside'],
    disposal_method: ['wooded', 'remote'],
    cause_of_death: ['strangulation'],
    signature_details: 'Kidnapped, sexually assaulted and killed women in Oakland County Michigan area.',
    wikipedia_slug: 'Leslie_Allen_Williams',
  },

  // ── SOUTH / SOUTHEAST ──────────────────────────────────────────────────────

  {
    name: 'Dean Corll',
    aliases: ['Candy Man', 'Houston Mass Murderer'],
    birth_year: 1939,
    status: 'deceased',
    conviction_count: 28, suspected_count: 28,
    active_from: 1970, active_to: 1973, incarcerated_from: 1973,
    home_states: ['TX'], home_cities: ['Houston', 'Pasadena'],
    operation_states: ['TX'], victim_states: ['TX'],
    victim_sex: 'male', victim_races: ['white', 'hispanic'],
    victim_age_min: 13, victim_age_max: 20, victim_age_typical: 16,
    mo_keywords: ['young_male', 'lured', 'candy', 'neighborhood'],
    disposal_method: ['buried', 'boat_shed', 'beach'],
    cause_of_death: ['strangulation', 'shooting'],
    signature_details: 'Used accomplices (Henley, Brooks) to lure boys. Torture board. Bodies buried in boat shed and on beach.',
    wikipedia_slug: 'Dean_Corll',
  },
  {
    name: 'Kenneth McDuff',
    aliases: ['Broomstick Killer'],
    birth_year: 1946,
    status: 'deceased',
    conviction_count: 3, suspected_count: 9,
    active_from: 1966, active_to: 1992, incarcerated_from: 1992,
    home_states: ['TX'], home_cities: ['Rosebud', 'Waco', 'Austin'],
    travel_corridors: ['I-35', 'US-77'],
    operation_states: ['TX'], victim_states: ['TX'],
    victim_sex: 'both', victim_races: ['white', 'black'],
    victim_age_min: 16, victim_age_max: 30, victim_age_typical: 22,
    mo_keywords: ['sex_worker', 'drug_user', 'car_wash', 'abduction'],
    disposal_method: ['roadside', 'remote', 'wooded'],
    cause_of_death: ['strangulation', 'blunt_force'],
    signature_details: 'Executed in 1998. Released from death row 1989 due to overcrowding, killed again. Targeted drug users and sex workers in Texas.',
    wikipedia_slug: 'Kenneth_McDuff',
  },
  {
    name: 'Tommy Lynn Sells',
    aliases: ['Coast to Coast Killer'],
    birth_year: 1964,
    status: 'deceased',
    conviction_count: 1, suspected_count: 22,
    active_from: 1980, active_to: 1999, incarcerated_from: 2000,
    home_states: ['TX', 'MO'],
    home_cities: ['Del Rio TX'],
    travel_corridors: ['I-10', 'I-20', 'I-35', 'I-40'],
    operation_states: ['TX', 'MO', 'TN', 'CA', 'ID', 'WV', 'KY', 'NV', 'IL', 'NE', 'UT'],
    victim_states: ['TX', 'MO', 'TN', 'CA'],
    victim_sex: 'both', victim_races: ['white', 'hispanic'],
    victim_age_min: 4, victim_age_max: 35, victim_age_typical: 20,
    mo_keywords: ['drifter', 'transient', 'hitchhiker', 'home_invasion', 'random'],
    disposal_method: ['left_in_place', 'remote', 'roadside'],
    cause_of_death: ['stabbing', 'strangulation', 'shooting'],
    signature_details: 'Itinerant drifter traveling by freight train and hitchhiking. Random opportunistic attacks across country. Confessed to multiple killings in many states.',
    wikipedia_slug: 'Tommy_Lynn_Sells',
  },
  {
    name: 'Robert Ben Rhoades',
    aliases: ['Truck Stop Killer'],
    birth_year: 1945,
    status: 'incarcerated',
    conviction_count: 3, suspected_count: 50,
    active_from: 1975, active_to: 1990, incarcerated_from: 1990,
    home_states: ['TX', 'IL'], home_cities: ['Houston', 'Chicago'],
    travel_corridors: ['I-10', 'I-20', 'I-40', 'I-80', 'I-94'],
    operation_states: ['TX', 'IL', 'AZ', 'UT', 'MT'],
    victim_states: ['TX', 'IL', 'AZ', 'UT'],
    victim_sex: 'both', victim_races: ['white'],
    victim_age_min: 14, victim_age_max: 30, victim_age_typical: 22,
    mo_keywords: ['truck_stop', 'long_haul_trucker', 'hitchhiker', 'highway_abduction'],
    disposal_method: ['roadside', 'remote', 'desert'],
    cause_of_death: ['strangulation', 'torture'],
    signature_details: 'Long-haul trucker with torture chamber in cab. Picked up hitchhikers at truck stops nationwide. Kept victims captive for days. FBI estimates 50+ victims.',
    wikipedia_slug: 'Robert_Ben_Rhoades',
  },
  {
    name: 'Derrick Todd Lee',
    aliases: ['Baton Rouge Serial Killer'],
    birth_year: 1968,
    status: 'deceased',
    conviction_count: 2, suspected_count: 7,
    active_from: 1992, active_to: 2003, incarcerated_from: 2004,
    home_states: ['LA'], home_cities: ['Baton Rouge', 'St. Francisville'],
    operation_states: ['LA'], victim_states: ['LA'],
    victim_sex: 'female', victim_races: ['white'],
    victim_age_min: 21, victim_age_max: 44, victim_age_typical: 28,
    mo_keywords: ['home_invasion', 'stalking', 'college_area'],
    disposal_method: ['left_in_place', 'wooded'],
    cause_of_death: ['blunt_force', 'strangulation'],
    signature_details: 'Attacked women in and around Baton Rouge including college students. DNA linked cases.',
    wikipedia_slug: 'Derrick_Todd_Lee',
  },
  {
    name: 'Gerald Stano',
    birth_year: 1951,
    status: 'deceased',
    conviction_count: 9, suspected_count: 41,
    active_from: 1969, active_to: 1980, incarcerated_from: 1982,
    home_states: ['FL', 'NJ', 'PA'], home_cities: ['Daytona Beach', 'Norristown'],
    operation_states: ['FL', 'NJ', 'PA', 'GA'],
    victim_states: ['FL', 'NJ', 'PA'],
    victim_sex: 'female', victim_races: ['white'],
    victim_age_min: 12, victim_age_max: 34, victim_age_typical: 20,
    mo_keywords: ['hitchhiker', 'sex_worker', 'bar', 'car_lure'],
    disposal_method: ['wooded', 'roadside', 'remote'],
    cause_of_death: ['stabbing', 'strangulation'],
    signature_details: 'Picked up hitchhikers and barroom women in car. Operated primarily along Florida coast.',
    wikipedia_slug: 'Gerald_Stano',
  },
  {
    name: 'Danny Rolling',
    aliases: ['Gainesville Ripper'],
    birth_year: 1954,
    status: 'deceased',
    conviction_count: 5, suspected_count: 8,
    active_from: 1989, active_to: 1990, incarcerated_from: 1991,
    home_states: ['FL', 'LA'], home_cities: ['Gainesville', 'Shreveport'],
    operation_states: ['FL', 'LA'], victim_states: ['FL', 'LA'],
    victim_sex: 'both', victim_races: ['white'],
    victim_age_min: 17, victim_age_max: 23, victim_age_typical: 20,
    mo_keywords: ['college_campus', 'home_invasion', 'stalking', 'posing'],
    disposal_method: ['left_in_place'],
    cause_of_death: ['stabbing'],
    signature_details: 'Attacked college students near University of Florida. Posed victims. Staged scenes.',
    wikipedia_slug: 'Danny_Rolling',
  },
  {
    name: 'David Alan Gore',
    birth_year: 1953,
    status: 'deceased',
    conviction_count: 6, suspected_count: 6,
    active_from: 1981, active_to: 1983, incarcerated_from: 1983,
    home_states: ['FL'], home_cities: ['Vero Beach', 'Indian River County'],
    operation_states: ['FL'], victim_states: ['FL'],
    victim_sex: 'female', victim_races: ['white'],
    victim_age_min: 14, victim_age_max: 35, victim_age_typical: 20,
    mo_keywords: ['hitchhiker', 'abduction', 'car', 'rural'],
    disposal_method: ['buried', 'remote', 'farm'],
    cause_of_death: ['shooting', 'strangulation'],
    signature_details: 'Operated with cousin Fred Waterfield. Picked up hitchhikers in Vero Beach area. Buried victims on rural property.',
    wikipedia_slug: 'David_Alan_Gore',
  },
  {
    name: 'Glen Rogers',
    aliases: ['Cross Country Killer', 'Casanova Killer'],
    birth_year: 1962,
    status: 'incarcerated',
    conviction_count: 4, suspected_count: 70,
    active_from: 1993, active_to: 1995, incarcerated_from: 1995,
    home_states: ['OH', 'CA', 'FL'],
    home_cities: ['Hamilton OH'],
    travel_corridors: ['I-10', 'I-75', 'I-40'],
    operation_states: ['CA', 'FL', 'TX', 'MS', 'TN', 'KY', 'OH', 'LA'],
    victim_states: ['CA', 'FL', 'TX', 'MS'],
    victim_sex: 'female', victim_races: ['white'],
    victim_age_min: 33, victim_age_max: 72, victim_age_typical: 50,
    mo_keywords: ['bar', 'dating', 'drifter', 'transient', 'con_artist'],
    disposal_method: ['left_in_place', 'wooded'],
    cause_of_death: ['stabbing', 'strangulation'],
    signature_details: 'Charming drifter who befriended and killed women. Cross-country killing spree 1995. Claimed 70+ victims.',
    wikipedia_slug: 'Glen_Rogers',
  },
  {
    name: 'Aileen Wuornos',
    birth_year: 1956,
    status: 'deceased',
    conviction_count: 6, suspected_count: 7,
    active_from: 1989, active_to: 1990, incarcerated_from: 1991,
    home_states: ['FL'], home_cities: ['Daytona Beach', 'Volusia County'],
    travel_corridors: ['I-75', 'I-95', 'I-4'],
    operation_states: ['FL'], victim_states: ['FL'],
    victim_sex: 'male', victim_races: ['white'],
    victim_age_min: 40, victim_age_max: 65, victim_age_typical: 55,
    mo_keywords: ['sex_worker', 'highway', 'car', 'truck_stop'],
    disposal_method: ['wooded', 'remote', 'roadside'],
    cause_of_death: ['shooting'],
    signature_details: 'Female serial killer. Sex worker who killed male clients along Florida highways. Claimed self-defense.',
    wikipedia_slug: 'Aileen_Wuornos',
  },
  {
    name: 'Donald Henry Gaskins',
    aliases: ['Pee Wee', 'Meanest Man in America'],
    birth_year: 1933,
    status: 'deceased',
    conviction_count: 9, suspected_count: 200,
    active_from: 1953, active_to: 1982, incarcerated_from: 1982,
    home_states: ['SC'], home_cities: ['Florence', 'Sumter'],
    travel_corridors: ['US-17', 'US-76'],
    operation_states: ['SC', 'NC', 'GA', 'FL'],
    victim_states: ['SC', 'NC', 'FL'],
    victim_sex: 'both', victim_races: ['white', 'black'],
    victim_age_min: 13, victim_age_max: 45, victim_age_typical: 22,
    mo_keywords: ['hitchhiker', 'drifter', 'highway', 'coastal_waterway'],
    disposal_method: ['roadside', 'water', 'buried'],
    cause_of_death: ['stabbing', 'shooting', 'blunt_force'],
    signature_details: 'Claimed to cruise coastal highways picking up hitchhikers. Distinguished "serious murders" from "recreational murders."',
    wikipedia_slug: 'Donald_Henry_Gaskins',
  },
  {
    name: 'Anthony Sowell',
    aliases: ['Cleveland Strangler'],
    birth_year: 1959,
    status: 'deceased',
    conviction_count: 11, suspected_count: 11,
    active_from: 2007, active_to: 2009, incarcerated_from: 2009,
    home_states: ['OH'], home_cities: ['Cleveland'],
    operation_states: ['OH'], victim_states: ['OH'],
    victim_sex: 'female', victim_races: ['black'],
    victim_age_min: 25, victim_age_max: 52, victim_age_typical: 38,
    mo_keywords: ['drug_user', 'marginalized', 'vulnerable', 'home_based'],
    disposal_method: ['in_structure', 'buried', 'backyard'],
    cause_of_death: ['strangulation'],
    signature_details: 'Targeted vulnerable Black women. Bodies stored in house and buried in backyard. Detected by odor.',
    wikipedia_slug: 'Anthony_Sowell',
  },
  {
    name: 'Richard Evonitz',
    birth_year: 1963,
    status: 'deceased',
    conviction_count: 3, suspected_count: 3,
    active_from: 1996, active_to: 2002, incarcerated_from: 2002,
    home_states: ['VA', 'SC'], home_cities: ['Spotsylvania VA', 'Columbia SC'],
    travel_corridors: ['I-95', 'I-77'],
    operation_states: ['VA', 'SC'], victim_states: ['VA', 'SC'],
    victim_sex: 'female', victim_races: ['white'],
    victim_age_min: 9, victim_age_max: 17, victim_age_typical: 13,
    mo_keywords: ['children', 'abduction', 'neighborhood', 'stalking'],
    disposal_method: ['water', 'remote'],
    cause_of_death: ['strangulation', 'asphyxiation'],
    signature_details: 'Abducted girls from neighborhoods in VA and SC. Suicide fleeing police 2002. Serial offender across state lines.',
    wikipedia_slug: 'Richard_Evonitz',
  },
  {
    name: 'Todd Kohlhepp',
    birth_year: 1971,
    status: 'incarcerated',
    conviction_count: 7, suspected_count: 7,
    active_from: 2003, active_to: 2016, incarcerated_from: 2016,
    home_states: ['SC'], home_cities: ['Woodruff', 'Spartanburg'],
    operation_states: ['SC', 'AZ'], victim_states: ['SC', 'AZ'],
    victim_sex: 'both', victim_races: ['white'],
    victim_age_min: 21, victim_age_max: 45, victim_age_typical: 30,
    mo_keywords: ['real_estate_ruse', 'remote_property', 'dating', 'captive'],
    disposal_method: ['buried', 'farm', 'remote'],
    cause_of_death: ['shooting'],
    signature_details: 'Real estate agent who lured victims to remote properties. Kept captive on farm. 2003 motorcycle shop mass shooting.',
    wikipedia_slug: 'Todd_Kohlhepp',
  },

  // ── MID-ATLANTIC / NORTHEAST ───────────────────────────────────────────────

  {
    name: 'Gary Heidnik',
    birth_year: 1943,
    status: 'deceased',
    conviction_count: 2, suspected_count: 2,
    active_from: 1986, active_to: 1987, incarcerated_from: 1987,
    home_states: ['PA'], home_cities: ['Philadelphia'],
    operation_states: ['PA', 'NJ'], victim_states: ['PA'],
    victim_sex: 'female', victim_races: ['black'],
    victim_age_min: 18, victim_age_max: 25, victim_age_typical: 22,
    mo_keywords: ['captive', 'lured', 'neighborhood', 'pit'],
    disposal_method: ['in_structure', 'dismembered'],
    cause_of_death: ['torture', 'strangulation'],
    signature_details: 'Kept six women captive in cellar pit in Philadelphia. Self-styled preacher. Partial inspiration for Silence of the Lambs character.',
    wikipedia_slug: 'Gary_Heidnik',
  },
  {
    name: 'Michael Ross',
    birth_year: 1959,
    status: 'deceased',
    conviction_count: 8, suspected_count: 8,
    active_from: 1981, active_to: 1984, incarcerated_from: 1984,
    home_states: ['CT'], home_cities: ['Jewett City', 'Moosup'],
    operation_states: ['CT', 'NY'], victim_states: ['CT', 'NY'],
    victim_sex: 'female', victim_races: ['white'],
    victim_age_min: 14, victim_age_max: 25, victim_age_typical: 17,
    mo_keywords: ['hitchhiker', 'abduction', 'rural', 'stalking'],
    disposal_method: ['wooded', 'remote'],
    cause_of_death: ['strangulation'],
    signature_details: 'Cornell graduate who targeted young women in rural Connecticut. Known as the Roadside Strangler.',
    wikipedia_slug: 'Michael_Ross_(murderer)',
  },
  {
    name: 'John Joseph Joubert',
    birth_year: 1963,
    status: 'deceased',
    conviction_count: 3, suspected_count: 4,
    active_from: 1982, active_to: 1983, incarcerated_from: 1983,
    home_states: ['NE', 'ME'], home_cities: ['Omaha', 'Scarborough ME'],
    operation_states: ['NE', 'ME'], victim_states: ['NE', 'ME'],
    victim_sex: 'male', victim_races: ['white'],
    victim_age_min: 9, victim_age_max: 13, victim_age_typical: 11,
    mo_keywords: ['children', 'abduction', 'suburban', 'military_base'],
    disposal_method: ['wooded', 'remote'],
    cause_of_death: ['stabbing', 'strangulation'],
    signature_details: 'Air Force enlisted man who targeted young boys near military bases. Bite mark evidence. Active in Maine and Nebraska.',
    wikipedia_slug: 'John_Joseph_Joubert',
  },

  // ── NATIONWIDE / TRAVELING ─────────────────────────────────────────────────

  {
    name: 'Henry Lee Lucas',
    birth_year: 1936,
    status: 'deceased',
    conviction_count: 3, suspected_count: 350,
    active_from: 1960, active_to: 1983, incarcerated_from: 1983,
    home_states: ['TX', 'VA', 'FL'],
    home_cities: ['Stoneburg TX'],
    travel_corridors: ['I-35', 'I-10', 'I-20'],
    operation_states: ['TX', 'FL', 'VA', 'CA', 'OR', 'WA', 'ID', 'OK', 'KS'],
    victim_states: ['TX', 'FL', 'VA', 'OR'],
    victim_sex: 'both', victim_races: ['white'],
    victim_age_min: 15, victim_age_max: 80, victim_age_typical: 30,
    mo_keywords: ['hitchhiker', 'transient', 'drifter', 'highway_abduction'],
    disposal_method: ['roadside', 'remote', 'wooded'],
    cause_of_death: ['stabbing', 'strangulation', 'blunt_force'],
    signature_details: 'Itinerant drifter. Traveled extensively. Claimed mass killings; many disputed. Confirmed kills include hitchhikers along southern/western highways.',
    wikipedia_slug: 'Henry_Lee_Lucas',
  },
  {
    name: 'Paul John Knowles',
    aliases: ['Casanova Killer'],
    birth_year: 1946,
    status: 'deceased',
    conviction_count: 18, suspected_count: 35,
    active_from: 1974, active_to: 1974, incarcerated_from: 1974,
    home_states: ['FL', 'GA'], home_cities: ['Jacksonville'],
    travel_corridors: ['I-75', 'I-20', 'I-10'],
    operation_states: ['FL', 'GA', 'AL', 'CA', 'NV', 'OH', 'SC', 'CT', 'VA'],
    victim_states: ['FL', 'GA', 'AL', 'OH'],
    victim_sex: 'both', victim_races: ['white'],
    victim_age_min: 11, victim_age_max: 65, victim_age_typical: 35,
    mo_keywords: ['hitchhiker', 'transient', 'drifter', 'opportunistic'],
    disposal_method: ['wooded', 'remote', 'water'],
    cause_of_death: ['strangulation', 'shooting', 'stabbing'],
    signature_details: 'Escaped prison July 1974, killed until November 1974. Multi-state rampage. Opportunistic — no consistent victim type.',
    wikipedia_slug: 'Paul_John_Knowles',
  },
  {
    name: 'Joseph Paul Franklin',
    birth_year: 1950,
    status: 'deceased',
    conviction_count: 8, suspected_count: 20,
    active_from: 1977, active_to: 1980, incarcerated_from: 1997,
    home_states: ['MO', 'TN', 'GA'],
    home_cities: ['St. Louis', 'Nashville'],
    travel_corridors: ['I-70', 'I-40', 'I-24'],
    operation_states: ['MO', 'TN', 'GA', 'WI', 'UT', 'OK', 'VA', 'FL', 'OH'],
    victim_states: ['MO', 'TN', 'GA', 'WI', 'UT'],
    victim_sex: 'both', victim_races: ['black', 'white'],
    victim_age_min: 15, victim_age_max: 42, victim_age_typical: 25,
    mo_keywords: ['racially_motivated', 'sniper', 'interracial_couple'],
    disposal_method: ['left_in_place'],
    cause_of_death: ['shooting'],
    signature_details: 'Racially motivated sniper attacks. Targeted interracial couples and Black individuals. Traveled widely across south and midwest.',
    wikipedia_slug: 'Joseph_Paul_Franklin',
  },
  {
    name: 'Christopher Wilder',
    aliases: ['Beauty Queen Killer'],
    birth_year: 1945,
    status: 'deceased',
    conviction_count: 0, suspected_count: 12,
    active_from: 1965, active_to: 1984, incarcerated_from: 1984,
    home_states: ['FL', 'TX', 'CA'], home_cities: ['Boca Raton'],
    travel_corridors: ['I-10', 'I-40', 'I-80'],
    operation_states: ['FL', 'TX', 'CA', 'NV', 'CO', 'KS', 'OK', 'LA', 'NY'],
    victim_states: ['FL', 'TX', 'CA', 'NV', 'NY'],
    victim_sex: 'female', victim_races: ['white'],
    victim_age_min: 17, victim_age_max: 24, victim_age_typical: 20,
    mo_keywords: ['modeling_ruse', 'photography_ruse', 'abduction', 'highway'],
    disposal_method: ['remote', 'wooded', 'water'],
    cause_of_death: ['strangulation', 'stabbing'],
    signature_details: 'Lured young women with modeling/photography offers. Cross-country killing spree spring 1984. Died in shootout with police.',
    wikipedia_slug: 'Christopher_Wilder',
  },
  {
    name: 'Coral Eugene Watts',
    aliases: ['Sunday Morning Slasher'],
    birth_year: 1953,
    status: 'deceased',
    conviction_count: 2, suspected_count: 80,
    active_from: 1974, active_to: 1982, incarcerated_from: 1982,
    home_states: ['MI', 'TX'], home_cities: ['Ann Arbor', 'Houston'],
    operation_states: ['MI', 'TX', 'IL', 'OH'],
    victim_states: ['MI', 'TX'],
    victim_sex: 'female', victim_races: ['white', 'black'],
    victim_age_min: 14, victim_age_max: 44, victim_age_typical: 23,
    mo_keywords: ['stalking', 'early_morning', 'jogging', 'opportunistic'],
    disposal_method: ['left_in_place', 'water', 'wooded'],
    cause_of_death: ['stabbing', 'strangulation', 'drowning'],
    signature_details: 'Early morning attacks on women, often joggers. No sexual assault. Texas plea gave him freedom 2006 before Michigan charges.',
    wikipedia_slug: 'Coral_Eugene_Watts',
  },
  {
    name: 'Angel Maturino Resendiz',
    aliases: ['Railroad Killer'],
    birth_year: 1960,
    status: 'deceased',
    conviction_count: 1, suspected_count: 15,
    active_from: 1997, active_to: 1999, incarcerated_from: 1999,
    home_states: ['TX'],
    home_cities: ['El Paso'],
    travel_corridors: ['I-10', 'I-20', 'I-30', 'railroad'],
    operation_states: ['TX', 'IL', 'KY', 'GA', 'CA', 'NM'],
    victim_states: ['TX', 'IL', 'KY'],
    victim_sex: 'both', victim_races: ['white', 'hispanic'],
    victim_age_min: 17, victim_age_max: 87, victim_age_typical: 45,
    mo_keywords: ['railroad', 'home_invasion', 'transient', 'drifter'],
    disposal_method: ['left_in_place'],
    cause_of_death: ['blunt_force', 'stabbing'],
    signature_details: 'Traveled US by freight train. Broke into homes near railway lines. Also known as "Railway Killer." Mexican national who crossed border repeatedly.',
    wikipedia_slug: 'Angel_Maturino_Resendiz',
  },

  // ── HIGHWAY / TRUCK CORRIDOR ───────────────────────────────────────────────

  {
    name: 'Interstate 70 Killer',
    aliases: ['I-70 Killer'],
    birth_year: undefined,
    status: 'unidentified',
    conviction_count: 0, suspected_count: 6,
    active_from: 1992, active_to: 1992,
    travel_corridors: ['I-70'],
    operation_states: ['MO', 'KS', 'IN', 'OH'],
    victim_states: ['MO', 'KS', 'IN'],
    victim_sex: 'female', victim_races: ['white'],
    victim_age_min: 20, victim_age_max: 35, victim_age_typical: 26,
    mo_keywords: ['retail_worker', 'shoe_store', 'small_business'],
    disposal_method: ['left_in_place'],
    cause_of_death: ['shooting'],
    signature_details: 'Shot female retail workers (predominantly shoe stores) along I-70 corridor. All occurred April–May 1992. Never identified.',
    wikipedia_slug: 'I-70_killer',
  },
  {
    name: 'John Allen Muhammad',
    aliases: ['Beltway Sniper'],
    birth_year: 1960,
    status: 'deceased',
    conviction_count: 2, suspected_count: 17,
    active_from: 1999, active_to: 2002, incarcerated_from: 2003,
    home_states: ['WA', 'MD'], home_cities: ['Tacoma', 'Bellingham'],
    travel_corridors: ['I-95', 'I-270', 'I-66'],
    operation_states: ['MD', 'VA', 'DC', 'WA', 'AL', 'CA', 'LA', 'GA', 'AZ'],
    victim_states: ['MD', 'VA', 'DC', 'WA'],
    victim_sex: 'both', victim_races: ['white', 'black', 'hispanic'],
    victim_age_min: 13, victim_age_max: 72, victim_age_typical: 40,
    mo_keywords: ['sniper', 'random', 'parking_lot', 'gas_station'],
    disposal_method: ['left_in_place'],
    cause_of_death: ['shooting'],
    signature_details: 'DC Sniper attacks October 2002 with John Lee Boyd Malvo. Operated from modified Chevy Caprice. Prior killings in multiple states.',
    wikipedia_slug: 'John_Allen_Muhammad',
  },

  // ── SOUTH / APPALACHIAN ────────────────────────────────────────────────────

  {
    name: 'Robert Durst',
    birth_year: 1943,
    status: 'deceased',
    conviction_count: 1, suspected_count: 3,
    active_from: 1982, active_to: 2000, incarcerated_from: 2021,
    home_states: ['NY', 'TX', 'CA'],
    home_cities: ['New York City', 'Galveston TX', 'Los Angeles'],
    operation_states: ['NY', 'TX', 'CA'],
    victim_states: ['NY', 'TX', 'CA'],
    victim_sex: 'both', victim_races: ['white'],
    victim_age_min: 29, victim_age_max: 55, victim_age_typical: 40,
    mo_keywords: ['domestic', 'acquaintance', 'wealthy', 'real_estate'],
    disposal_method: ['dismembered', 'water', 'left_in_place'],
    cause_of_death: ['strangulation', 'shooting'],
    signature_details: 'Wealthy real estate heir. Convicted 2021 for murder of Susan Berman. Suspected in wife\'s disappearance 1982. Dismembered neighbor in Galveston.',
    wikipedia_slug: 'Robert_Durst',
  },
  {
    name: 'Shawn Grate',
    birth_year: 1980,
    status: 'incarcerated',
    conviction_count: 5, suspected_count: 5,
    active_from: 2015, active_to: 2016, incarcerated_from: 2016,
    home_states: ['OH'], home_cities: ['Ashland', 'Richland County'],
    operation_states: ['OH'], victim_states: ['OH'],
    victim_sex: 'female', victim_races: ['white'],
    victim_age_min: 26, victim_age_max: 55, victim_age_typical: 40,
    mo_keywords: ['vulnerable_women', 'abandoned_building', 'online_dating'],
    disposal_method: ['in_structure', 'abandoned_building'],
    cause_of_death: ['strangulation'],
    signature_details: 'Kept bodies in abandoned buildings. Lured women through social media. Caught when one victim escaped.',
    wikipedia_slug: 'Shawn_Grate',
  },
  {
    name: 'Darren Deon Vann',
    birth_year: 1971,
    status: 'incarcerated',
    conviction_count: 7, suspected_count: 7,
    active_from: 2013, active_to: 2014, incarcerated_from: 2014,
    home_states: ['IN'], home_cities: ['Gary', 'Hammond'],
    operation_states: ['IN'], victim_states: ['IN'],
    victim_sex: 'female', victim_races: ['black'],
    victim_age_min: 19, victim_age_max: 49, victim_age_typical: 35,
    mo_keywords: ['sex_worker', 'motel', 'marginalized'],
    disposal_method: ['abandoned_building', 'left_in_place'],
    cause_of_death: ['strangulation'],
    signature_details: 'Targeted sex workers in Gary Indiana. Bodies found in abandoned buildings. Prior rape conviction in Texas.',
    wikipedia_slug: 'Darren_Deon_Vann',
  },
  {
    name: 'Mark Goudeau',
    aliases: ['Baseline Killer'],
    birth_year: 1964,
    status: 'incarcerated',
    conviction_count: 9, suspected_count: 9,
    active_from: 2005, active_to: 2006, incarcerated_from: 2006,
    home_states: ['AZ'], home_cities: ['Phoenix'],
    operation_states: ['AZ'], victim_states: ['AZ'],
    victim_sex: 'both', victim_races: ['hispanic', 'white'],
    victim_age_min: 13, victim_age_max: 52, victim_age_typical: 28,
    mo_keywords: ['parking_lot', 'random', 'suburban', 'night_attack'],
    disposal_method: ['left_in_place'],
    cause_of_death: ['shooting', 'stabbing'],
    signature_details: 'Phoenix attacks along Baseline Road. Mix of robbery, sexual assault, and murder. Targeted Hispanics and women disproportionately.',
    wikipedia_slug: 'Mark_Goudeau',
  },

  // ── APPALACHIAN / RURAL ────────────────────────────────────────────────────

  {
    name: 'Jerome Henry Brudos',
    aliases: ['Shoe Fetish Slayer', 'Lust Killer'],
    birth_year: 1939,
    status: 'deceased',
    conviction_count: 4, suspected_count: 4,
    active_from: 1968, active_to: 1969, incarcerated_from: 1969,
    home_states: ['OR'], home_cities: ['Salem', 'Portland'],
    operation_states: ['OR'], victim_states: ['OR'],
    victim_sex: 'female', victim_races: ['white'],
    victim_age_min: 16, victim_age_max: 23, victim_age_typical: 19,
    mo_keywords: ['hitchhiker', 'lured', 'shoe_fetish', 'abduction'],
    disposal_method: ['water', 'river', 'weighted'],
    cause_of_death: ['strangulation'],
    signature_details: 'Shoe and foot fetishist. Abducted women near Oregon State University. Dumped weighted bodies in Willamette River.',
    wikipedia_slug: 'Jerry_Brudos',
  },
  {
    name: 'Stephen Pennell',
    aliases: ['Corridor Killer'],
    birth_year: 1957,
    status: 'deceased',
    conviction_count: 2, suspected_count: 5,
    active_from: 1987, active_to: 1988, incarcerated_from: 1988,
    home_states: ['DE'], home_cities: ['Bear', 'New Castle County'],
    travel_corridors: ['US-40', 'I-95'],
    operation_states: ['DE'], victim_states: ['DE'],
    victim_sex: 'female', victim_races: ['white'],
    victim_age_min: 23, victim_age_max: 35, victim_age_typical: 28,
    mo_keywords: ['sex_worker', 'highway_abduction', 'van', 'us40'],
    disposal_method: ['roadside', 'wooded'],
    cause_of_death: ['blunt_force', 'torture'],
    signature_details: 'Picked up sex workers along US-40 corridor in Delaware. Torture van. Hair fiber evidence conviction.',
    wikipedia_slug: 'Stephen_Pennell',
  },
  {
    name: 'Carroll Edward Cole',
    birth_year: 1938,
    status: 'deceased',
    conviction_count: 3, suspected_count: 16,
    active_from: 1971, active_to: 1980, incarcerated_from: 1984,
    home_states: ['NV', 'TX', 'CA'], home_cities: ['Las Vegas', 'San Diego'],
    operation_states: ['NV', 'TX', 'CA', 'WY', 'OK'],
    victim_states: ['NV', 'TX', 'CA'],
    victim_sex: 'female', victim_races: ['white'],
    victim_age_min: 25, victim_age_max: 45, victim_age_typical: 35,
    mo_keywords: ['bar', 'alcohol', 'transient', 'drifter', 'strangulation'],
    disposal_method: ['left_in_place', 'concealed'],
    cause_of_death: ['strangulation'],
    signature_details: 'Targeted solitary women in bars. Strangled victims in their homes. Traveled between states. Executed 1985.',
    wikipedia_slug: 'Carroll_Edward_Cole',
  },
  {
    name: 'Thomas Lee Dillon',
    birth_year: 1950,
    status: 'incarcerated',
    conviction_count: 5, suspected_count: 5,
    active_from: 1989, active_to: 1992, incarcerated_from: 1992,
    home_states: ['OH'], home_cities: ['Jackson', 'Massillon'],
    operation_states: ['OH'], victim_states: ['OH'],
    victim_sex: 'male', victim_races: ['white'],
    victim_age_min: 21, victim_age_max: 44, victim_age_typical: 33,
    mo_keywords: ['hunting', 'rural', 'outdoors', 'random_shooting'],
    disposal_method: ['left_in_place', 'roadside'],
    cause_of_death: ['shooting'],
    signature_details: 'Targeted hunters, fishermen, and hikers in rural Ohio. Random shootings from vehicle. Caught through hunting club letter.',
    wikipedia_slug: 'Thomas_Lee_Dillon',
  },
  {
    name: 'Paul Michael Stephani',
    aliases: ['Weepy-Voiced Killer'],
    birth_year: 1944,
    status: 'deceased',
    conviction_count: 1, suspected_count: 3,
    active_from: 1980, active_to: 1982, incarcerated_from: 1982,
    home_states: ['MN'], home_cities: ['Minneapolis', 'St. Paul'],
    operation_states: ['MN'], victim_states: ['MN'],
    victim_sex: 'female', victim_races: ['white'],
    victim_age_min: 18, victim_age_max: 27, victim_age_typical: 22,
    mo_keywords: ['hitchhiker', 'bar', 'night', 'downtown'],
    disposal_method: ['alley', 'roadside', 'left_in_place'],
    cause_of_death: ['stabbing'],
    signature_details: 'Called 911 weeping after attacks. Targeted young women at night in Minneapolis. Died in prison of cancer.',
    wikipedia_slug: 'Paul_Michael_Stephani',
  },
  {
    name: 'Daniel Lee Siebert',
    birth_year: 1951,
    status: 'deceased',
    conviction_count: 4, suspected_count: 7,
    active_from: 1979, active_to: 1986, incarcerated_from: 1986,
    home_states: ['AL', 'CA'], home_cities: ['Talladega AL', 'San Diego CA'],
    operation_states: ['AL', 'CA', 'GA'],
    victim_states: ['AL', 'CA'],
    victim_sex: 'both', victim_races: ['black', 'white'],
    victim_age_min: 4, victim_age_max: 36, victim_age_typical: 25,
    mo_keywords: ['hitchhiker', 'acquaintance', 'drifter'],
    disposal_method: ['remote', 'wooded', 'roadside'],
    cause_of_death: ['stabbing', 'strangulation', 'drowning'],
    signature_details: 'Operated in Alabama and California. Killed family members and acquaintances as well as strangers. Executed 2008.',
    wikipedia_slug: 'Daniel_Siebert',
  },
  {
    name: 'Tim Krajcir',
    birth_year: 1944,
    status: 'incarcerated',
    conviction_count: 9, suspected_count: 11,
    active_from: 1977, active_to: 1982, incarcerated_from: 2007,
    home_states: ['IL', 'MO'], home_cities: ['Cape Girardeau MO', 'Carbondale IL'],
    operation_states: ['IL', 'MO', 'TN', 'KY', 'PA'],
    victim_states: ['IL', 'MO', 'TN', 'KY'],
    victim_sex: 'female', victim_races: ['white', 'black'],
    victim_age_min: 19, victim_age_max: 65, victim_age_typical: 35,
    mo_keywords: ['home_invasion', 'stalking', 'abduction', 'random'],
    disposal_method: ['left_in_place', 'remote', 'wooded'],
    cause_of_death: ['shooting', 'strangulation'],
    signature_details: 'Missouri/Illinois border region. Cases unsolved 25 years. Confessed to cold cases 2007 after DNA match. Psychology degree from prison.',
    wikipedia_slug: 'Timothy_Krajcir',
  },
  {
    name: 'Marc Sappington',
    aliases: ['Kansas City Vampire'],
    birth_year: 1981,
    status: 'incarcerated',
    conviction_count: 3, suspected_count: 4,
    active_from: 2001, active_to: 2001, incarcerated_from: 2001,
    home_states: ['MO'], home_cities: ['Kansas City'],
    operation_states: ['MO'], victim_states: ['MO'],
    victim_sex: 'male', victim_races: ['black'],
    victim_age_min: 16, victim_age_max: 22, victim_age_typical: 19,
    mo_keywords: ['acquaintance', 'neighborhood', 'young_male', 'drug_induced'],
    disposal_method: ['left_in_place', 'alley'],
    cause_of_death: ['stabbing', 'shooting'],
    signature_details: 'Heard voices commanding killing. Drank victim blood. Three killings in 10 days, Kansas City.',
    wikipedia_slug: 'Marc_Sappington',
  },
  {
    name: 'Harvey Robinson',
    aliases: ['Allentown Strangler'],
    birth_year: 1974,
    status: 'incarcerated',
    conviction_count: 3, suspected_count: 5,
    active_from: 1992, active_to: 1993, incarcerated_from: 1993,
    home_states: ['PA'], home_cities: ['Allentown', 'Lehigh County'],
    operation_states: ['PA'], victim_states: ['PA'],
    victim_sex: 'female', victim_races: ['white'],
    victim_age_min: 14, victim_age_max: 47, victim_age_typical: 20,
    mo_keywords: ['home_invasion', 'suburban', 'stalking', 'night_entry'],
    disposal_method: ['left_in_place'],
    cause_of_death: ['strangulation', 'blunt_force'],
    signature_details: 'Broke into homes at night in Allentown PA. Young offender — 19 at time of first known killing.',
    wikipedia_slug: 'Harvey_Robinson',
  },
  {
    name: 'Gerald Gallego',
    birth_year: 1946,
    status: 'deceased',
    conviction_count: 2, suspected_count: 10,
    active_from: 1978, active_to: 1980, incarcerated_from: 1983,
    home_states: ['CA', 'NV'], home_cities: ['Sacramento', 'Reno'],
    travel_corridors: ['I-80', 'US-50'],
    operation_states: ['CA', 'NV', 'OR', 'WA'],
    victim_states: ['CA', 'NV'],
    victim_sex: 'female', victim_races: ['white'],
    victim_age_min: 13, victim_age_max: 22, victim_age_typical: 16,
    mo_keywords: ['young_female', 'van_abduction', 'mall', 'sex_slave_fantasy'],
    disposal_method: ['remote', 'desert', 'rural'],
    cause_of_death: ['shooting', 'blunt_force'],
    signature_details: 'Operated with wife Charlene Williams as lure. Abducted pairs of young women from malls/fairs using van. "Sex slave" fantasy.',
    wikipedia_slug: 'Gerald_Gallego',
  },
  {
    name: 'David Parker Ray',
    aliases: ['Toy Box Killer'],
    birth_year: 1939,
    status: 'deceased',
    conviction_count: 0, suspected_count: 60,
    active_from: 1959, active_to: 1999, incarcerated_from: 1999,
    home_states: ['NM'], home_cities: ['Elephant Butte', 'Truth or Consequences'],
    operation_states: ['NM', 'TX', 'AZ'],
    victim_states: ['NM'],
    victim_sex: 'female', victim_races: ['white', 'hispanic'],
    victim_age_min: 18, victim_age_max: 40, victim_age_typical: 28,
    mo_keywords: ['remote', 'captive', 'sex_worker', 'hitchhiker', 'torture'],
    disposal_method: ['remote', 'lake', 'buried'],
    cause_of_death: ['torture', 'unknown'],
    signature_details: 'Custom-built "toy box" torture trailer near Elephant Butte Lake NM. Accomplices including girlfriend Cindy Hendy. No bodies ever confirmed found.',
    wikipedia_slug: 'David_Parker_Ray',
  },
  {
    name: 'Michael Gargiulo',
    aliases: ['Hollywood Ripper'],
    birth_year: 1976,
    status: 'incarcerated',
    conviction_count: 2, suspected_count: 3,
    active_from: 1993, active_to: 2008, incarcerated_from: 2008,
    home_states: ['CA', 'IL'], home_cities: ['Los Angeles', 'Glenview IL'],
    operation_states: ['CA', 'IL'], victim_states: ['CA', 'IL'],
    victim_sex: 'female', victim_races: ['white'],
    victim_age_min: 18, victim_age_max: 32, victim_age_typical: 23,
    mo_keywords: ['stalking', 'neighbor', 'home_invasion', 'night_entry'],
    disposal_method: ['left_in_place'],
    cause_of_death: ['stabbing'],
    signature_details: 'Stalked and attacked women in their homes. Neighbors of victims. Los Angeles and suburban Chicago. Dated Ashley Ellerin (victim).',
    wikipedia_slug: 'Michael_Gargiulo',
  },
  {
    name: 'Joseph Kondro',
    birth_year: 1958,
    status: 'deceased',
    conviction_count: 2, suspected_count: 4,
    active_from: 1979, active_to: 1997, incarcerated_from: 1997,
    home_states: ['WA'], home_cities: ['Longview', 'Kelso'],
    operation_states: ['WA', 'OR'], victim_states: ['WA'],
    victim_sex: 'female', victim_races: ['white'],
    victim_age_min: 6, victim_age_max: 13, victim_age_typical: 9,
    mo_keywords: ['children', 'neighborhood', 'lured', 'acquaintance'],
    disposal_method: ['wooded', 'remote'],
    cause_of_death: ['strangulation', 'asphyxiation'],
    signature_details: 'Killed girls in Longview WA area. Cases separated by decades. Died in prison. DNA connected cold cases.',
    wikipedia_slug: 'Joseph_Kondro',
  },
  {
    name: 'Jack Owen Spillman III',
    aliases: ['Werewolf Killer'],
    birth_year: 1969,
    status: 'incarcerated',
    conviction_count: 3, suspected_count: 3,
    active_from: 1995, active_to: 1995, incarcerated_from: 1995,
    home_states: ['WA'], home_cities: ['Cashmere', 'Wenatchee'],
    operation_states: ['WA'], victim_states: ['WA'],
    victim_sex: 'female', victim_races: ['white'],
    victim_age_min: 8, victim_age_max: 42, victim_age_typical: 22,
    mo_keywords: ['home_invasion', 'rural', 'family', 'stabbing'],
    disposal_method: ['left_in_place', 'remote'],
    cause_of_death: ['stabbing', 'strangulation'],
    signature_details: 'Killed family members and a third victim in rural Chelan County WA. Ritualistic elements.',
    wikipedia_slug: 'Jack_Owen_Spillman',
  },
  {
    name: 'William Lester Suff',
    aliases: ['Riverside Prostitute Killer', 'Lake Elsinore Killer'],
    birth_year: 1950,
    status: 'incarcerated',
    conviction_count: 12, suspected_count: 14,
    active_from: 1986, active_to: 1991, incarcerated_from: 1992,
    home_states: ['CA'], home_cities: ['Lake Elsinore', 'Riverside'],
    operation_states: ['CA'], victim_states: ['CA'],
    victim_sex: 'female', victim_races: ['white', 'hispanic', 'black'],
    victim_age_min: 14, victim_age_max: 38, victim_age_typical: 25,
    mo_keywords: ['sex_worker', 'highway_abduction', 'car', 'riverside_county'],
    disposal_method: ['dumpster', 'roadside', 'alley'],
    cause_of_death: ['strangulation', 'stabbing'],
    signature_details: 'Targeted sex workers in Riverside County CA over 5 years. County employee. Evidence of posing and mutilation.',
    wikipedia_slug: 'William_Lester_Suff',
  },
  {
    name: 'Cleophus Prince Jr.',
    aliases: ['Clairemont Killer'],
    birth_year: 1967,
    status: 'incarcerated',
    conviction_count: 6, suspected_count: 6,
    active_from: 1990, active_to: 1990, incarcerated_from: 1990,
    home_states: ['CA'], home_cities: ['San Diego'],
    operation_states: ['CA'], victim_states: ['CA'],
    victim_sex: 'female', victim_races: ['white'],
    victim_age_min: 18, victim_age_max: 44, victim_age_typical: 28,
    mo_keywords: ['home_invasion', 'suburban', 'apartment', 'stalking'],
    disposal_method: ['left_in_place'],
    cause_of_death: ['stabbing'],
    signature_details: 'Broke into apartments in Clairemont neighborhood San Diego. Six stabbing murders in four months.',
    wikipedia_slug: 'Cleophus_Prince_Jr.',
  },
  {
    name: 'Wayne Williams',
    aliases: ['Atlanta Child Murderer'],
    birth_year: 1958,
    status: 'incarcerated',
    conviction_count: 2, suspected_count: 29,
    active_from: 1979, active_to: 1981, incarcerated_from: 1982,
    home_states: ['GA'], home_cities: ['Atlanta'],
    operation_states: ['GA'], victim_states: ['GA'],
    victim_sex: 'both', victim_races: ['black'],
    victim_age_min: 7, victim_age_max: 28, victim_age_typical: 13,
    mo_keywords: ['young_black_male', 'lured', 'neighborhood', 'music_ruse'],
    disposal_method: ['water', 'river', 'wooded'],
    cause_of_death: ['strangulation', 'asphyxiation'],
    signature_details: 'Targeted young Black boys and young adults in Atlanta. Bodies dumped in rivers. Fiber evidence key to conviction.',
    wikipedia_slug: 'Wayne_Williams',
  },
  // ── SOUTHEAST COAST ────────────────────────────────────────────────────────

  {
    name: 'Ottis Toole',
    birth_year: 1947,
    status: 'deceased',
    conviction_count: 6, suspected_count: 50,
    active_from: 1973, active_to: 1983, incarcerated_from: 1983,
    home_states: ['FL'], home_cities: ['Jacksonville'],
    travel_corridors: ['I-10', 'I-75', 'I-95'],
    operation_states: ['FL', 'TX', 'OK', 'AR', 'LA', 'MS', 'AL', 'GA'],
    victim_states: ['FL', 'TX'],
    victim_sex: 'both', victim_races: ['white', 'black'],
    victim_age_min: 6, victim_age_max: 65, victim_age_typical: 30,
    mo_keywords: ['drifter', 'transient', 'hitchhiker', 'opportunistic', 'arson'],
    disposal_method: ['roadside', 'remote', 'fire'],
    cause_of_death: ['stabbing', 'strangulation', 'shooting'],
    signature_details: 'Accomplice and partner of Henry Lee Lucas. Itinerant drifter. Confessed to killing Adam Walsh (disputed). Compulsive arsonist.',
    wikipedia_slug: 'Ottis_Toole',
  },
  {
    name: 'Larry Gene Bell',
    birth_year: 1949,
    status: 'deceased',
    conviction_count: 2, suspected_count: 2,
    active_from: 1985, active_to: 1985, incarcerated_from: 1985,
    home_states: ['SC'], home_cities: ['Saluda', 'Lexington County'],
    operation_states: ['SC'], victim_states: ['SC'],
    victim_sex: 'female', victim_races: ['white'],
    victim_age_min: 9, victim_age_max: 17, victim_age_typical: 13,
    mo_keywords: ['children', 'abduction', 'suburban', 'stalking'],
    disposal_method: ['wooded', 'remote'],
    cause_of_death: ['asphyxiation', 'strangulation'],
    signature_details: 'Abducted girls from suburban Columbia SC area. Made taunting phone calls to victims\' families. Executed 1996.',
    wikipedia_slug: 'Larry_Gene_Bell',
  },
  {
    name: 'Tim Spencer',
    aliases: ['South Side Strangler'],
    birth_year: 1962,
    status: 'deceased',
    conviction_count: 4, suspected_count: 4,
    active_from: 1987, active_to: 1987, incarcerated_from: 1987,
    home_states: ['VA'], home_cities: ['Richmond', 'Arlington'],
    operation_states: ['VA'], victim_states: ['VA'],
    victim_sex: 'female', victim_races: ['white'],
    victim_age_min: 15, victim_age_max: 44, victim_age_typical: 30,
    mo_keywords: ['home_invasion', 'stalking', 'suburban', 'abduction'],
    disposal_method: ['left_in_place', 'wooded'],
    cause_of_death: ['strangulation'],
    signature_details: 'First US conviction using DNA evidence. Attacked women in Richmond and Arlington VA. Concurrent with another attacker (David Vasquez).',
    wikipedia_slug: 'Timothy_Wilson_Spencer',
  },
  {
    name: 'Charles Cullen',
    aliases: ['Angel of Death'],
    birth_year: 1960,
    status: 'incarcerated',
    conviction_count: 29, suspected_count: 400,
    active_from: 1988, active_to: 2003, incarcerated_from: 2003,
    home_states: ['NJ', 'PA'], home_cities: ['Bethlehem PA', 'Allentown PA'],
    operation_states: ['NJ', 'PA'], victim_states: ['NJ', 'PA'],
    victim_sex: 'both', victim_races: ['white', 'black'],
    victim_age_min: 21, victim_age_max: 91, victim_age_typical: 70,
    mo_keywords: ['hospital', 'nurse', 'overdose', 'elderly', 'medication'],
    disposal_method: ['hospital', 'left_in_place'],
    cause_of_death: ['poisoning', 'overdose'],
    signature_details: 'ICU nurse who killed patients with medication overdoses. Worked at 9 hospitals across NJ and PA over 16 years.',
    wikipedia_slug: 'Charles_Cullen',
  },
  {
    name: 'Robert Pickton',
    aliases: ['Pig Farm Killer'],
    birth_year: 1949,
    status: 'incarcerated',
    conviction_count: 6, suspected_count: 49,
    active_from: 1983, active_to: 2001, incarcerated_from: 2002,
    home_states: ['BC'], home_cities: ['Port Coquitlam', 'Vancouver'],
    operation_states: ['BC'], victim_states: ['BC'],
    victim_sex: 'female', victim_races: ['white', 'indigenous'],
    victim_age_min: 26, victim_age_max: 52, victim_age_typical: 35,
    mo_keywords: ['sex_worker', 'drug_user', 'skid_row', 'marginalized'],
    disposal_method: ['farm', 'pig_pen', 'buried'],
    cause_of_death: ['shooting', 'strangulation'],
    signature_details: 'Targeted sex workers from Vancouver Downtown Eastside. Brought victims to Port Coquitlam farm.',
    wikipedia_slug: 'Robert_Pickton',
  },
  {
    name: 'Ivan Milat',
    aliases: ['Backpacker Killer'],
    birth_year: 1944,
    status: 'deceased',
    conviction_count: 7, suspected_count: 9,
    active_from: 1989, active_to: 1992, incarcerated_from: 1996,
    home_states: ['NSW'],
    home_cities: ['Eaglevale Sydney'],
    travel_corridors: ['Hume Highway'],
    operation_states: ['NSW'],
    victim_states: ['NSW'],
    victim_sex: 'both', victim_races: ['white'],
    victim_age_min: 19, victim_age_max: 22, victim_age_typical: 21,
    mo_keywords: ['hitchhiker', 'backpacker', 'tourist', 'highway'],
    disposal_method: ['wooded', 'remote', 'buried'],
    cause_of_death: ['stabbing', 'shooting', 'strangulation'],
    signature_details: 'Targeted backpackers hitchhiking between Sydney and Melbourne. Bodies found in Belanglo State Forest.',
    wikipedia_slug: 'Ivan_Milat',
  },

  // ── NORTHEAST / NEW ENGLAND ────────────────────────────────────────────────

  {
    name: 'Gary Michael Hilton',
    aliases: ['National Forest Killer'],
    birth_year: 1946,
    status: 'incarcerated',
    conviction_count: 4, suspected_count: 4,
    active_from: 2007, active_to: 2008, incarcerated_from: 2008,
    home_states: ['GA', 'FL'], home_cities: ['Atlanta', 'Tallahassee'],
    travel_corridors: ['I-75', 'I-95', 'Appalachian Trail'],
    operation_states: ['GA', 'FL', 'NC', 'WV'],
    victim_states: ['GA', 'FL', 'NC', 'WV'],
    victim_sex: 'both', victim_races: ['white'],
    victim_age_min: 24, victim_age_max: 80, victim_age_typical: 45,
    mo_keywords: ['national_park', 'hiking_trail', 'wilderness', 'remote'],
    disposal_method: ['remote', 'wilderness', 'wooded'],
    cause_of_death: ['blunt_force', 'decapitation'],
    signature_details: 'Targeted hikers and campers in national forests and parks along southeast. Traveled in van.',
    wikipedia_slug: 'Gary_Michael_Hilton',
  },
  {
    name: 'John Floyd Thomas Jr.',
    aliases: ['Westside Rapist'],
    birth_year: 1940,
    status: 'incarcerated',
    conviction_count: 7, suspected_count: 30,
    active_from: 1972, active_to: 2006, incarcerated_from: 2009,
    home_states: ['CA'], home_cities: ['Los Angeles'],
    operation_states: ['CA'], victim_states: ['CA'],
    victim_sex: 'female', victim_races: ['white'],
    victim_age_min: 55, victim_age_max: 94, victim_age_typical: 75,
    mo_keywords: ['elderly', 'home_invasion', 'stalking', 'west_la'],
    disposal_method: ['left_in_place'],
    cause_of_death: ['strangulation', 'blunt_force'],
    signature_details: 'Specifically targeted elderly women in West LA over three decades. Cold case DNA match 2009.',
    wikipedia_slug: 'John_Floyd_Thomas_Jr.',
  },
  {
    name: 'Billy Chemirmir',
    birth_year: 1977,
    status: 'incarcerated',
    conviction_count: 2, suspected_count: 24,
    active_from: 2016, active_to: 2018, incarcerated_from: 2018,
    home_states: ['TX'], home_cities: ['Dallas', 'Plano'],
    operation_states: ['TX'], victim_states: ['TX'],
    victim_sex: 'female', victim_races: ['white'],
    victim_age_min: 76, victim_age_max: 94, victim_age_typical: 85,
    mo_keywords: ['elderly', 'nursing_home', 'smothering', 'robbery'],
    disposal_method: ['left_in_place'],
    cause_of_death: ['asphyxiation', 'smothering'],
    signature_details: 'Targeted elderly women in independent and assisted living facilities in Dallas area. Stole jewelry.',
    wikipedia_slug: 'Billy_Chemirmir',
  },
  {
    name: 'Nathaniel Bar-Jonah',
    birth_year: 1957,
    status: 'deceased',
    conviction_count: 1, suspected_count: 2,
    active_from: 1977, active_to: 1999, incarcerated_from: 1999,
    home_states: ['MT', 'MA'], home_cities: ['Great Falls MT', 'Worcester MA'],
    operation_states: ['MT', 'MA'], victim_states: ['MT', 'MA'],
    victim_sex: 'male', victim_races: ['white'],
    victim_age_min: 5, victim_age_max: 12, victim_age_typical: 8,
    mo_keywords: ['children', 'abduction', 'neighborhood', 'lured'],
    disposal_method: ['remote', 'wooded'],
    cause_of_death: ['asphyxiation', 'blunt_force'],
    signature_details: 'Multiple assaults on children across MA and MT. Prior convictions for attacks on children. Suspected in disappearance of Zachary Ramsay.',
    wikipedia_slug: 'Nathaniel_Bar-Jonah',
  },
  {
    name: 'Joseph Christopher',
    aliases: ['22 Caliber Killer', '.22 Caliber Killer'],
    birth_year: 1955,
    status: 'deceased',
    conviction_count: 3, suspected_count: 13,
    active_from: 1980, active_to: 1981, incarcerated_from: 1981,
    home_states: ['NY'], home_cities: ['Buffalo', 'New York City'],
    operation_states: ['NY', 'GA'],
    victim_states: ['NY'],
    victim_sex: 'male', victim_races: ['black'],
    victim_age_min: 14, victim_age_max: 71, victim_age_typical: 35,
    mo_keywords: ['racially_motivated', 'random', 'street', 'stabbing_spree'],
    disposal_method: ['left_in_place'],
    cause_of_death: ['stabbing', 'shooting'],
    signature_details: 'Racially motivated attacks on Black men in Buffalo NY area. Also stabbed patients at Fort Benning. Targeted at random on streets.',
    wikipedia_slug: 'Joseph_Christopher',
  },
  {
    name: 'John Bittrolff',
    birth_year: 1966,
    status: 'incarcerated',
    conviction_count: 2, suspected_count: 4,
    active_from: 1993, active_to: 1994, incarcerated_from: 2014,
    home_states: ['NY'], home_cities: ['Manorville', 'Long Island'],
    operation_states: ['NY'], victim_states: ['NY'],
    victim_sex: 'female', victim_races: ['white'],
    victim_age_min: 22, victim_age_max: 30, victim_age_typical: 26,
    mo_keywords: ['sex_worker', 'highway', 'long_island'],
    disposal_method: ['wooded', 'roadside'],
    cause_of_death: ['strangulation'],
    signature_details: 'Convicted 2015 of 1993–94 Long Island sex worker killings. DNA solved cold case. Possible connection to Long Island Serial Killer cluster.',
    wikipedia_slug: 'John_Bittrolff',
  },
  {
    name: 'Richard Biegenwald',
    aliases: ['Thrill Killer'],
    birth_year: 1940,
    status: 'deceased',
    conviction_count: 5, suspected_count: 9,
    active_from: 1958, active_to: 1983, incarcerated_from: 1983,
    home_states: ['NJ'], home_cities: ['Asbury Park', 'Ocean County'],
    operation_states: ['NJ', 'NY'], victim_states: ['NJ'],
    victim_sex: 'female', victim_races: ['white'],
    victim_age_min: 17, victim_age_max: 35, victim_age_typical: 20,
    mo_keywords: ['hitchhiker', 'young_woman', 'shore', 'buried'],
    disposal_method: ['buried', 'wooded', 'remote'],
    cause_of_death: ['shooting', 'strangulation'],
    signature_details: 'New Jersey shore area. Two distinct active periods separated by incarceration. Buried victims.',
    wikipedia_slug: 'Richard_Biegenwald',
  },
  {
    name: 'Stephen Gerald Morin',
    birth_year: 1950,
    status: 'deceased',
    conviction_count: 3, suspected_count: 20,
    active_from: 1973, active_to: 1981, incarcerated_from: 1981,
    home_states: ['TX', 'MN'], home_cities: ['San Antonio'],
    travel_corridors: ['I-35', 'I-10'],
    operation_states: ['TX', 'MN', 'CO', 'MI', 'CA'],
    victim_states: ['TX', 'MN', 'CO'],
    victim_sex: 'female', victim_races: ['white'],
    victim_age_min: 18, victim_age_max: 28, victim_age_typical: 22,
    mo_keywords: ['hitchhiker', 'car_lure', 'drifter', 'highway'],
    disposal_method: ['roadside', 'remote', 'wooded'],
    cause_of_death: ['stabbing', 'strangulation'],
    signature_details: 'Itinerant drifter. Confessed to 20+ killings across multiple states. Executed 1985 Texas. Born-again Christian on death row.',
    wikipedia_slug: 'Stephen_Morin_(serial_killer)',
  },
  {
    name: 'Maurice Byrd',
    birth_year: 1956,
    status: 'deceased',
    conviction_count: 4, suspected_count: 6,
    active_from: 1980, active_to: 1983, incarcerated_from: 1983,
    home_states: ['MO'], home_cities: ['St. Louis'],
    operation_states: ['MO'], victim_states: ['MO'],
    victim_sex: 'both', victim_races: ['white'],
    victim_age_min: 14, victim_age_max: 45, victim_age_typical: 30,
    mo_keywords: ['robbery', 'opportunistic', 'home_invasion', 'bar'],
    disposal_method: ['left_in_place'],
    cause_of_death: ['shooting'],
    signature_details: 'St. Louis area. Multiple robberies escalating to murder. Executed 1991 Missouri.',
    source_notes: 'Missouri Department of Corrections records.',
  },
  {
    name: 'Michael Lee Lockhart',
    birth_year: 1960,
    status: 'deceased',
    conviction_count: 3, suspected_count: 8,
    active_from: 1984, active_to: 1987, incarcerated_from: 1987,
    home_states: ['TX', 'FL', 'IN'],
    home_cities: ['Beaumont TX'],
    travel_corridors: ['I-10', 'I-75', 'I-65'],
    operation_states: ['TX', 'FL', 'IN', 'OH'],
    victim_states: ['TX', 'FL', 'IN'],
    victim_sex: 'both', victim_races: ['white'],
    victim_age_min: 14, victim_age_max: 35, victim_age_typical: 22,
    mo_keywords: ['hitchhiker', 'drifter', 'highway', 'robbery'],
    disposal_method: ['left_in_place', 'roadside'],
    cause_of_death: ['shooting', 'stabbing'],
    signature_details: 'Drifting career criminal who killed across Texas, Florida and Indiana. Killed police officer in Indiana. Executed 1997.',
    wikipedia_slug: 'Michael_Lee_Lockhart',
  },
  {
    name: 'Vaughn Greenwood',
    aliases: ['Skid Row Slasher'],
    birth_year: 1944,
    status: 'incarcerated',
    conviction_count: 11, suspected_count: 14,
    active_from: 1964, active_to: 1976, incarcerated_from: 1976,
    home_states: ['CA'], home_cities: ['Los Angeles'],
    operation_states: ['CA'], victim_states: ['CA'],
    victim_sex: 'male', victim_races: ['white', 'black'],
    victim_age_min: 40, victim_age_max: 65, victim_age_typical: 55,
    mo_keywords: ['skid_row', 'homeless', 'transient', 'ritual'],
    disposal_method: ['left_in_place', 'alley'],
    cause_of_death: ['stabbing'],
    signature_details: 'Targeted homeless men on Skid Row Los Angeles. Placed salt in shoe soles, cups of blood near bodies. Active in two separate periods.',
    wikipedia_slug: 'Vaughn_Greenwood',
  },
  {
    name: 'James Nathaniel Russell',
    aliases: ['Raiford Slasher'],
    birth_year: 1940,
    status: 'deceased',
    conviction_count: 4, suspected_count: 4,
    active_from: 1990, active_to: 1997, incarcerated_from: 1997,
    home_states: ['FL'], home_cities: ['Bradford County', 'Gainesville'],
    operation_states: ['FL'], victim_states: ['FL'],
    victim_sex: 'both', victim_races: ['white', 'black'],
    victim_age_min: 16, victim_age_max: 55, victim_age_typical: 30,
    mo_keywords: ['rural', 'acquaintance', 'north_florida'],
    disposal_method: ['remote', 'wooded'],
    cause_of_death: ['stabbing', 'blunt_force'],
    source_notes: 'Florida Department of Corrections records.',
  },
  {
    name: 'Anthony Allen Shore',
    aliases: ['Tourniquet Killer'],
    birth_year: 1962,
    status: 'deceased',
    conviction_count: 4, suspected_count: 4,
    active_from: 1986, active_to: 1994, incarcerated_from: 1998,
    home_states: ['TX'], home_cities: ['Houston'],
    operation_states: ['TX'], victim_states: ['TX'],
    victim_sex: 'female', victim_races: ['white', 'hispanic'],
    victim_age_min: 9, victim_age_max: 21, victim_age_typical: 14,
    mo_keywords: ['children', 'abduction', 'neighborhood', 'ligature'],
    disposal_method: ['alley', 'dumpster', 'left_in_place'],
    cause_of_death: ['strangulation'],
    signature_details: 'Houston area. Ligature strangulation using improvised tourniquet. Targeted girls and young women. Executed 2018.',
    wikipedia_slug: 'Anthony_Shore',
  },
  {
    name: 'Reginald Artis',
    birth_year: 1950,
    status: 'incarcerated',
    conviction_count: 2, suspected_count: 5,
    active_from: 1979, active_to: 1984, incarcerated_from: 1985,
    home_states: ['OH'], home_cities: ['Dayton', 'Montgomery County'],
    operation_states: ['OH'], victim_states: ['OH'],
    victim_sex: 'female', victim_races: ['black'],
    victim_age_min: 18, victim_age_max: 35, victim_age_typical: 25,
    mo_keywords: ['sex_worker', 'bar', 'acquaintance', 'strangulation'],
    disposal_method: ['left_in_place', 'roadside'],
    cause_of_death: ['strangulation'],
    source_notes: 'Ohio court records. Dayton area sex worker murders.',
  },
  {
    name: 'Craig Price',
    aliases: ['Warwick Slasher'],
    birth_year: 1973,
    status: 'incarcerated',
    conviction_count: 4, suspected_count: 4,
    active_from: 1987, active_to: 1989, incarcerated_from: 1989,
    home_states: ['RI'], home_cities: ['Warwick'],
    operation_states: ['RI'], victim_states: ['RI'],
    victim_sex: 'female', victim_races: ['white'],
    victim_age_min: 9, victim_age_max: 39, victim_age_typical: 20,
    mo_keywords: ['neighborhood', 'home_invasion', 'children', 'stabbing'],
    disposal_method: ['left_in_place'],
    cause_of_death: ['stabbing'],
    signature_details: 'Began killing at age 13 in Warwick RI. Only juvenile serial killer to commit multiple murders. Currently serving additional sentences.',
    wikipedia_slug: 'Craig_Price',
  },
]

async function main() {
  const isDryRun = process.argv.includes('--dry-run')
  console.log(`\nSeeding ${OFFENDERS.length} known offenders${isDryRun ? ' (DRY RUN)' : ''}...\n`)

  if (isDryRun) {
    OFFENDERS.forEach(o => {
      const years = `${o.active_from ?? '?'}–${o.active_to ?? '?'}`
      const conv = o.conviction_count ?? '?'
      const susp = o.suspected_count ?? '?'
      console.log(`  · ${o.name} (${conv}conv/${susp}susp) ${years} [${(o.home_states ?? []).join(',')}→${(o.operation_states ?? []).join(',')}]`)
    })
    console.log(`\n[DRY RUN] Total: ${OFFENDERS.length} offenders. No changes made.\n`)
    return
  }

  // Remove duplicates by name in seed data
  const seen = new Set<string>()
  const deduped = OFFENDERS.filter(o => {
    if (seen.has(o.name)) { console.warn(`  ⚠ Duplicate skipped: ${o.name}`); return false }
    seen.add(o.name)
    return true
  })

  // Clear existing rows then insert fresh
  console.log('Clearing existing rows...')
  await supabase.from('known_offenders').delete().neq('id', '00000000-0000-0000-0000-000000000000')

  let inserted = 0
  for (let i = 0; i < deduped.length; i += 20) {
    const batch = deduped.slice(i, i + 20)
    const { data, error } = await supabase
      .from('known_offenders')
      .insert(batch as never)
      .select('id, name')

    if (error) { console.error(`Batch error (${i}):`, error.message); continue }
    inserted += data?.length ?? 0
    process.stdout.write(`  Inserted ${inserted}/${deduped.length}...\r`)
  }

  console.log(`\n✓ Done — ${inserted} offender profiles seeded\n`)
}

main().catch(e => { console.error(e); process.exit(1) })
