-- ─── Doe Network cross-match candidates ──────────────────────────────────────
-- Stores pairwise match scores between:
--   (a) missing person submissions  ↔  unidentified remains submissions
-- Generated by /api/pattern/doe-match
-- ALL records require investigator review — high score ≠ confirmed match.

CREATE TABLE doe_match_candidates (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),

  missing_submission_id      UUID NOT NULL REFERENCES submissions(id) ON DELETE CASCADE,
  unidentified_submission_id UUID NOT NULL REFERENCES submissions(id) ON DELETE CASCADE,
  missing_case_id            UUID NOT NULL REFERENCES cases(id) ON DELETE CASCADE,
  unidentified_case_id       UUID NOT NULL REFERENCES cases(id) ON DELETE CASCADE,

  composite_score INTEGER NOT NULL,
  grade TEXT NOT NULL CHECK (grade IN ('weak','moderate','notable','strong','very_strong')),

  -- Full signal breakdown — see scoring engine for schema
  signals JSONB NOT NULL DEFAULT '{}',

  -- Denormalized display fields (populated at match time, avoids re-parsing)
  missing_doe_id    TEXT,
  missing_name      TEXT,
  missing_sex       TEXT,
  missing_race      TEXT,
  missing_age       TEXT,
  missing_location  TEXT,
  missing_date      TEXT,
  missing_hair      TEXT,
  missing_eyes      TEXT,
  missing_marks     TEXT,

  unidentified_doe_id    TEXT,
  unidentified_sex       TEXT,
  unidentified_race      TEXT,
  unidentified_age       TEXT,
  unidentified_location  TEXT,
  unidentified_date      TEXT,
  unidentified_hair      TEXT,
  unidentified_eyes      TEXT,
  unidentified_marks     TEXT,

  -- Reviewer workflow
  reviewer_status TEXT NOT NULL DEFAULT 'unreviewed'
    CHECK (reviewer_status IN ('unreviewed','worth_investigating','confirmed','dismissed')),
  reviewed_by   UUID REFERENCES auth.users(id),
  reviewed_at   TIMESTAMPTZ,
  reviewer_note TEXT,

  generated_at TIMESTAMPTZ NOT NULL DEFAULT now(),

  UNIQUE(missing_submission_id, unidentified_submission_id)
);

CREATE INDEX ON doe_match_candidates(composite_score DESC);
CREATE INDEX ON doe_match_candidates(grade);
CREATE INDEX ON doe_match_candidates(reviewer_status);
CREATE INDEX ON doe_match_candidates(missing_case_id);
CREATE INDEX ON doe_match_candidates(unidentified_case_id);
CREATE INDEX ON doe_match_candidates(missing_case_id, unidentified_case_id, grade);

-- ─── Victimology clusters ─────────────────────────────────────────────────────
-- Stores groups of missing persons that share demographics + location + temporal
-- pattern — e.g. "8 Black teen girls, Virginia, disappeared in spring, 2000–2020"

CREATE TABLE doe_victimology_clusters (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  case_id UUID NOT NULL REFERENCES cases(id) ON DELETE CASCADE,

  cluster_label TEXT NOT NULL,
  -- Types: 'demographic_temporal' | 'corridor_demographic' | 'circumstance_signal'
  cluster_type  TEXT NOT NULL,

  -- Demographic fields (for demographic_* types)
  sex           TEXT,
  race          TEXT,
  age_group     TEXT,
  state         TEXT,
  corridor      TEXT,

  -- Temporal fields
  temporal_pattern TEXT,
  year_span_start  INTEGER,
  year_span_end    INTEGER,
  case_count       INTEGER NOT NULL,

  -- Circumstance signal fields (for circumstance_signal type)
  primary_signal    TEXT,   -- e.g. 'foster_care'
  signal_category   TEXT,   -- e.g. 'social_context'
  matched_signals   TEXT[],  -- all signals present in this cluster

  submission_ids UUID[] NOT NULL DEFAULT '{}',
  signals        JSONB NOT NULL DEFAULT '{}',

  -- AI-generated narrative (populated on demand)
  ai_narrative      TEXT,
  ai_generated_at   TIMESTAMPTZ,

  reviewer_status TEXT NOT NULL DEFAULT 'unreviewed'
    CHECK (reviewer_status IN ('unreviewed','worth_investigating','confirmed','dismissed')),
  reviewed_by   UUID REFERENCES auth.users(id),
  reviewed_at   TIMESTAMPTZ,
  reviewer_note TEXT,

  generated_at TIMESTAMPTZ NOT NULL DEFAULT now()
);

CREATE INDEX ON doe_victimology_clusters(case_id);
CREATE INDEX ON doe_victimology_clusters(case_count DESC);
CREATE INDEX ON doe_victimology_clusters(reviewer_status);
CREATE INDEX ON doe_victimology_clusters(cluster_type);
CREATE INDEX ON doe_victimology_clusters(primary_signal);

-- ─── RLS ──────────────────────────────────────────────────────────────────────

ALTER TABLE doe_match_candidates ENABLE ROW LEVEL SECURITY;
ALTER TABLE doe_victimology_clusters ENABLE ROW LEVEL SECURITY;

-- Read: any case member
CREATE POLICY "case members can read doe_match_candidates"
  ON doe_match_candidates FOR SELECT
  USING (
    EXISTS (
      SELECT 1 FROM case_user_roles
      WHERE case_user_roles.case_id = doe_match_candidates.missing_case_id
        AND case_user_roles.user_id = auth.uid()
    )
  );

-- Insert/update: lead_investigator or admin only
CREATE POLICY "lead or admin can insert doe_match_candidates"
  ON doe_match_candidates FOR INSERT
  WITH CHECK (
    EXISTS (
      SELECT 1 FROM case_user_roles
      WHERE case_user_roles.case_id = doe_match_candidates.missing_case_id
        AND case_user_roles.user_id = auth.uid()
        AND case_user_roles.role IN ('lead_investigator','admin')
    )
  );

CREATE POLICY "lead or admin can update doe_match_candidates"
  ON doe_match_candidates FOR UPDATE
  USING (
    EXISTS (
      SELECT 1 FROM case_user_roles
      WHERE case_user_roles.case_id = doe_match_candidates.missing_case_id
        AND case_user_roles.user_id = auth.uid()
        AND case_user_roles.role IN ('lead_investigator','admin')
    )
  );

-- Victimology clusters
CREATE POLICY "case members can read doe_victimology_clusters"
  ON doe_victimology_clusters FOR SELECT
  USING (
    EXISTS (
      SELECT 1 FROM case_user_roles
      WHERE case_user_roles.case_id = doe_victimology_clusters.case_id
        AND case_user_roles.user_id = auth.uid()
    )
  );

CREATE POLICY "lead or admin can insert doe_victimology_clusters"
  ON doe_victimology_clusters FOR INSERT
  WITH CHECK (
    EXISTS (
      SELECT 1 FROM case_user_roles
      WHERE case_user_roles.case_id = doe_victimology_clusters.case_id
        AND case_user_roles.user_id = auth.uid()
        AND case_user_roles.role IN ('lead_investigator','admin')
    )
  );

CREATE POLICY "lead or admin can update doe_victimology_clusters"
  ON doe_victimology_clusters FOR UPDATE
  USING (
    EXISTS (
      SELECT 1 FROM case_user_roles
      WHERE case_user_roles.case_id = doe_victimology_clusters.case_id
        AND case_user_roles.user_id = auth.uid()
        AND case_user_roles.role IN ('lead_investigator','admin')
    )
  );
