-- =============================================================================
-- 027: Volunteer Skills & Expertise Matching
-- Users self-identify skills. Cases surface to people who can actually help.
-- =============================================================================

-- Skills a user can offer
CREATE TABLE IF NOT EXISTS user_skills (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  user_id UUID NOT NULL REFERENCES auth.users(id) ON DELETE CASCADE,
  skill TEXT NOT NULL CHECK (skill IN (
    'osint',              -- Open source intelligence, social media research
    'genealogy',          -- Family tree research, DNA genealogy
    'forensic_art',       -- Facial reconstruction, age progression
    'journalism',         -- Media outreach, FOIA requests, public records
    'legal',              -- Court records, legal research, case law
    'data_analysis',      -- Pattern analysis, statistics, data visualization
    'geospatial',         -- GIS, mapping, terrain analysis
    'medical_forensic',   -- Medical/forensic knowledge
    'languages',          -- Translation, non-English source research
    'law_enforcement',    -- Current or former LE experience
    'victim_advocacy',    -- Family support, grief counseling, advocacy
    'local_knowledge'     -- Deep knowledge of a specific region
  )),
  proficiency TEXT DEFAULT 'intermediate' CHECK (proficiency IN ('beginner', 'intermediate', 'expert', 'professional')),
  notes TEXT,             -- "I have access to Ancestry.com and newspapers.com"
  region TEXT,            -- "Virginia" or "Southeast US" — for local_knowledge
  available_hours TEXT,   -- "5-10 hours/week"
  created_at TIMESTAMPTZ DEFAULT now(),
  UNIQUE(user_id, skill)
);

CREATE INDEX idx_user_skills_skill ON user_skills(skill);
CREATE INDEX idx_user_skills_user ON user_skills(user_id);

-- What a case needs — auto-generated by AI or set manually
-- These are stored on import_records so "Cases That Need You" can match
ALTER TABLE import_records ADD COLUMN IF NOT EXISTS needs_skills TEXT[] DEFAULT '{}';

-- RLS
ALTER TABLE user_skills ENABLE ROW LEVEL SECURITY;

CREATE POLICY "skills_own" ON user_skills
  FOR ALL TO authenticated USING (auth.uid() = user_id);

-- Others can see your skills (for community matching)
CREATE POLICY "skills_read" ON user_skills
  FOR SELECT TO authenticated USING (true);
